package ma.oracle.apps.cx.realestate.setup.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 24 15:35:11 EET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MAAttachedDocumentsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MAAttachedDocumentsVOImpl() {
    }
}

