package ma.oracle.apps.cx.realestate.property.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 17 12:48:38 EET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MAFinancialVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MAFinancialVOImpl() {
    }
}

