package ma.oracle.apps.cx.realestate.property.views;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 02 14:02:17 EEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MAFloorNumberVVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        LookupCode {
            public Object get(MAFloorNumberVVORowImpl obj) {
                return obj.getLookupCode();
            }

            public void put(MAFloorNumberVVORowImpl obj, Object value) {
                obj.setLookupCode((String)value);
            }
        }
        ,
        FloorNumber {
            public Object get(MAFloorNumberVVORowImpl obj) {
                return obj.getFloorNumber();
            }

            public void put(MAFloorNumberVVORowImpl obj, Object value) {
                obj.setFloorNumber((String)value);
            }
        }
        ,
        LookupType {
            public Object get(MAFloorNumberVVORowImpl obj) {
                return obj.getLookupType();
            }

            public void put(MAFloorNumberVVORowImpl obj, Object value) {
                obj.setLookupType((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(MAFloorNumberVVORowImpl object);

        public abstract void put(MAFloorNumberVVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int LOOKUPCODE = AttributesEnum.LookupCode.index();
    public static final int FLOORNUMBER = AttributesEnum.FloorNumber.index();
    public static final int LOOKUPTYPE = AttributesEnum.LookupType.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MAFloorNumberVVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute LookupCode.
     * @return the LookupCode
     */
    public String getLookupCode() {
        return (String) getAttributeInternal(LOOKUPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LookupCode.
     * @param value value to set the  LookupCode
     */
    public void setLookupCode(String value) {
        setAttributeInternal(LOOKUPCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FloorNumber.
     * @return the FloorNumber
     */
    public String getFloorNumber() {
        return (String) getAttributeInternal(FLOORNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FloorNumber.
     * @param value value to set the  FloorNumber
     */
    public void setFloorNumber(String value) {
        setAttributeInternal(FLOORNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LookupType.
     * @return the LookupType
     */
    public String getLookupType() {
        return (String) getAttributeInternal(LOOKUPTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LookupType.
     * @param value value to set the  LookupType
     */
    public void setLookupType(String value) {
        setAttributeInternal(LOOKUPTYPE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
