package ma.oracle.apps.cx.realestate.property.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 07 15:06:14 EEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MAGenericViewVVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MAGenericViewVVOImpl() {
    }

    /**
     * Returns the variable value for b_property_id.
     * @return variable value for b_property_id
     */
    public Number getb_property_id() {
        return (Number)ensureVariableManager().getVariableValue("b_property_id");
    }

    /**
     * Sets <code>value</code> for variable b_property_id.
     * @param value value to bind as b_property_id
     */
    public void setb_property_id(Number value) {
        ensureVariableManager().setVariableValue("b_property_id", value);
    }

    /**
     * Returns the variable value for b_property_name.
     * @return variable value for b_property_name
     */
    public String getb_property_name() {
        return (String)ensureVariableManager().getVariableValue("b_property_name");
    }

    /**
     * Sets <code>value</code> for variable b_property_name.
     * @param value value to bind as b_property_name
     */
    public void setb_property_name(String value) {
        ensureVariableManager().setVariableValue("b_property_name", value);
    }


}
