package ma.oracle.apps.cx.realestate.property.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 19 14:10:06 EET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MAPropertyStatusVVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MAPropertyStatusVVOImpl() {
    }
}

