package ma.oracle.apps.cx.realestate.property.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 07 12:32:33 EEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MARealEstatePropertyTypesVVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MARealEstatePropertyTypesVVOImpl() {
    }
}
