package ma.oracle.apps.cx.realestate.property.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 07 12:37:57 EEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MARealEstatepropertyparentVVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PropertyId {
            public Object get(MARealEstatepropertyparentVVORowImpl obj) {
                return obj.getPropertyId();
            }

            public void put(MARealEstatepropertyparentVVORowImpl obj,
                            Object value) {
                obj.setPropertyId((Number)value);
            }
        }
        ,
        PropertySegment {
            public Object get(MARealEstatepropertyparentVVORowImpl obj) {
                return obj.getPropertySegment();
            }

            public void put(MARealEstatepropertyparentVVORowImpl obj,
                            Object value) {
                obj.setPropertySegment((String)value);
            }
        }
        ,
        PropertyName {
            public Object get(MARealEstatepropertyparentVVORowImpl obj) {
                return obj.getPropertyName();
            }

            public void put(MARealEstatepropertyparentVVORowImpl obj,
                            Object value) {
                obj.setPropertyName((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(MARealEstatepropertyparentVVORowImpl object);

        public abstract void put(MARealEstatepropertyparentVVORowImpl object,
                                 Object value);

        public int index() {
            return MARealEstatepropertyparentVVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return MARealEstatepropertyparentVVORowImpl.AttributesEnum.firstIndex() + MARealEstatepropertyparentVVORowImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = MARealEstatepropertyparentVVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PROPERTYID = AttributesEnum.PropertyId.index();
    public static final int PROPERTYSEGMENT = AttributesEnum.PropertySegment.index();
    public static final int PROPERTYNAME = AttributesEnum.PropertyName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MARealEstatepropertyparentVVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute PropertyId.
     * @return the PropertyId
     */
    public Number getPropertyId() {
        return (Number) getAttributeInternal(PROPERTYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PropertyId.
     * @param value value to set the  PropertyId
     */
    public void setPropertyId(Number value) {
        setAttributeInternal(PROPERTYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PropertySegment.
     * @return the PropertySegment
     */
    public String getPropertySegment() {
        return (String) getAttributeInternal(PROPERTYSEGMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PropertySegment.
     * @param value value to set the  PropertySegment
     */
    public void setPropertySegment(String value) {
        setAttributeInternal(PROPERTYSEGMENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PropertyName.
     * @return the PropertyName
     */
    public String getPropertyName() {
        return (String) getAttributeInternal(PROPERTYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PropertyName.
     * @param value value to set the  PropertyName
     */
    public void setPropertyName(String value) {
        setAttributeInternal(PROPERTYNAME, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
