package ma.oracle.apps.cx.realestate.property.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 27 12:04:52 EEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MARealEstatePropertyVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MARealEstatePropertyVOImpl() {
    }

    /**
     * Returns the variable value for b_property_id.
     * @return variable value for b_property_id
     */
    public Number getb_property_id() {
        return (Number)ensureVariableManager().getVariableValue("b_property_id");
    }

    /**
     * Sets <code>value</code> for variable b_property_id.
     * @param value value to bind as b_property_id
     */
    public void setb_property_id(Number value) {
        ensureVariableManager().setVariableValue("b_property_id", value);
    }

    /**
     * Returns the variable value for b_block_building_name.
     * @return variable value for b_block_building_name
     */
    public String getb_block_building_name() {
        return (String)ensureVariableManager().getVariableValue("b_block_building_name");
    }

    /**
     * Sets <code>value</code> for variable b_block_building_name.
     * @param value value to bind as b_block_building_name
     */
    public void setb_block_building_name(String value) {
        ensureVariableManager().setVariableValue("b_block_building_name", value);
    }

    /**
     * Returns the variable value for b_floor_number.
     * @return variable value for b_floor_number
     */
    public Number getb_floor_number() {
        return (Number)ensureVariableManager().getVariableValue("b_floor_number");
    }

    /**
     * Sets <code>value</code> for variable b_floor_number.
     * @param value value to bind as b_floor_number
     */
    public void setb_floor_number(Number value) {
        ensureVariableManager().setVariableValue("b_floor_number", value);
    }

    /**
     * Returns the variable value for b_rent_from.
     * @return variable value for b_rent_from
     */
    public Number getb_rent_from() {
        return (Number)ensureVariableManager().getVariableValue("b_rent_from");
    }

    /**
     * Sets <code>value</code> for variable b_rent_from.
     * @param value value to bind as b_rent_from
     */
    public void setb_rent_from(Number value) {
        ensureVariableManager().setVariableValue("b_rent_from", value);
    }

    /**
     * Returns the variable value for b_rent_to.
     * @return variable value for b_rent_to
     */
    public Number getb_rent_to() {
        return (Number)ensureVariableManager().getVariableValue("b_rent_to");
    }

    /**
     * Sets <code>value</code> for variable b_rent_to.
     * @param value value to bind as b_rent_to
     */
    public void setb_rent_to(Number value) {
        ensureVariableManager().setVariableValue("b_rent_to", value);
    }

    /**
     * Returns the variable value for b_unit_sq_from.
     * @return variable value for b_unit_sq_from
     */
    public Number getb_unit_sq_from() {
        return (Number)ensureVariableManager().getVariableValue("b_unit_sq_from");
    }

    /**
     * Sets <code>value</code> for variable b_unit_sq_from.
     * @param value value to bind as b_unit_sq_from
     */
    public void setb_unit_sq_from(Number value) {
        ensureVariableManager().setVariableValue("b_unit_sq_from", value);
    }

    /**
     * Returns the variable value for b_unit_sq_to.
     * @return variable value for b_unit_sq_to
     */
    public Number getb_unit_sq_to() {
        return (Number)ensureVariableManager().getVariableValue("b_unit_sq_to");
    }

    /**
     * Sets <code>value</code> for variable b_unit_sq_to.
     * @param value value to bind as b_unit_sq_to
     */
    public void setb_unit_sq_to(Number value) {
        ensureVariableManager().setVariableValue("b_unit_sq_to", value);
    }

    /**
     * Returns the variable value for b_status.
     * @return variable value for b_status
     */
    public String getb_status() {
        return (String)ensureVariableManager().getVariableValue("b_status");
    }

    /**
     * Sets <code>value</code> for variable b_status.
     * @param value value to bind as b_status
     */
    public void setb_status(String value) {
        ensureVariableManager().setVariableValue("b_status", value);
    }

    /**
     * Returns the variable value for b_property_name.
     * @return variable value for b_property_name
     */
    public String getb_property_name() {
        return (String)ensureVariableManager().getVariableValue("b_property_name");
    }

    /**
     * Sets <code>value</code> for variable b_property_name.
     * @param value value to bind as b_property_name
     */
    public void setb_property_name(String value) {
        ensureVariableManager().setVariableValue("b_property_name", value);
    }

    /**
     * Returns the variable value for b_number_rooms.
     * @return variable value for b_number_rooms
     */
    public Number getb_number_rooms() {
        return (Number)ensureVariableManager().getVariableValue("b_number_rooms");
    }

    /**
     * Sets <code>value</code> for variable b_number_rooms.
     * @param value value to bind as b_number_rooms
     */
    public void setb_number_rooms(Number value) {
        ensureVariableManager().setVariableValue("b_number_rooms", value);
    }
}
