package ma.oracle.apps.cx.realestate.property.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 25 14:39:04 EET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MARealEstatePaternPropVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MARealEstatePaternPropVOImpl() {
    }
}

