package ma.oracle.apps.cx.realestate.lease.entities;



import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 06 22:02:28 EEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MARealEstateleaseEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        LeaseId {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getLeaseId();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setLeaseId((Number)value);
            }
        }
        ,
        LeaseSegment {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getLeaseSegment();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setLeaseSegment((String)value);
            }
        }
        ,
        Subject {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getSubject();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setSubject((String)value);
            }
        }
        ,
        LeaserName {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getLeaserName();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setLeaserName((String)value);
            }
        }
        ,
        LeaserAddress {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getLeaserAddress();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setLeaserAddress((String)value);
            }
        }
        ,
        ContactPerson {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getContactPerson();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setContactPerson((String)value);
            }
        }
        ,
        ContactPhoneNumber {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getContactPhoneNumber();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setContactPhoneNumber((String)value);
            }
        }
        ,
        ContactEmail {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getContactEmail();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setContactEmail((String)value);
            }
        }
        ,
        OpportunityId {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getOpportunityId();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setOpportunityId((Number)value);
            }
        }
        ,
        LeaseStatus {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getLeaseStatus();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setLeaseStatus((String)value);
            }
        }
        ,
        LeaseType {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getLeaseType();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setLeaseType((String)value);
            }
        }
        ,
        TreinnelPercentage {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getTreinnelPercentage();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setTreinnelPercentage((Number)value);
            }
        }
        ,
        ParentLease {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getParentLease();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setParentLease((String)value);
            }
        }
        ,
        StartDate {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getStartDate();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setStartDate((Date)value);
            }
        }
        ,
        EndDate {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getEndDate();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setEndDate((Date)value);
            }
        }
        ,
        BookingExpiringOn {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getBookingExpiringOn();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setBookingExpiringOn((Date)value);
            }
        }
        ,
        Increase {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getIncrease();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setIncrease((String)value);
            }
        }
        ,
        IterationMonths {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getIterationMonths();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setIterationMonths((Number)value);
            }
        }
        ,
        AutoCalculateFlag {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAutoCalculateFlag();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAutoCalculateFlag((String)value);
            }
        }
        ,
        TenureMonths {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getTenureMonths();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setTenureMonths((String)value);
            }
        }
        ,
        LeaseTermsConditions {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getLeaseTermsConditions();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setLeaseTermsConditions((String)value);
            }
        }
        ,
        BillingFrequency {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getBillingFrequency();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setBillingFrequency((String)value);
            }
        }
        ,
        Water {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getWater();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setWater((Number)value);
            }
        }
        ,
        Electricity {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getElectricity();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setElectricity((Number)value);
            }
        }
        ,
        Sanitation {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getSanitation();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setSanitation((Number)value);
            }
        }
        ,
        Badge {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getBadge();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setBadge((Number)value);
            }
        }
        ,
        Discount {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getDiscount();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setDiscount((Number)value);
            }
        }
        ,
        Currency {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getCurrency();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        RentAmount {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getRentAmount();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setRentAmount((Number)value);
            }
        }
        ,
        AdhockCharges {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAdhockCharges();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAdhockCharges((Number)value);
            }
        }
        ,
        GrossRentAmount {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getGrossRentAmount();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setGrossRentAmount((Number)value);
            }
        }
        ,
        DiscountAmount {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getDiscountAmount();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setDiscountAmount((Number)value);
            }
        }
        ,
        NetAmount {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getNetAmount();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setNetAmount((Number)value);
            }
        }
        ,
        RenewalNoticeSent {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getRenewalNoticeSent();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setRenewalNoticeSent((Date)value);
            }
        }
        ,
        ReceivedConfirmationDate {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getReceivedConfirmationDate();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setReceivedConfirmationDate((Date)value);
            }
        }
        ,
        CustomerResponse {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getCustomerResponse();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setCustomerResponse((String)value);
            }
        }
        ,
        ProposedYearlyRent {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getProposedYearlyRent();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setProposedYearlyRent((String)value);
            }
        }
        ,
        VacantDate {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getVacantDate();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setVacantDate((Date)value);
            }
        }
        ,
        ExtendedDate {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getExtendedDate();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setExtendedDate((Date)value);
            }
        }
        ,
        TerminationNoticeSent {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getTerminationNoticeSent();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setTerminationNoticeSent((Date)value);
            }
        }
        ,
        TerminationDate {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getTerminationDate();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setTerminationDate((Date)value);
            }
        }
        ,
        TerminationReason {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getTerminationReason();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setTerminationReason((String)value);
            }
        }
        ,
        TerminationReasonDetails {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getTerminationReasonDetails();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setTerminationReasonDetails((String)value);
            }
        }
        ,
        AdminCharges {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAdminCharges();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAdminCharges((Number)value);
            }
        }
        ,
        AdminChargesApprovalFlag {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAdminChargesApprovalFlag();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAdminChargesApprovalFlag((String)value);
            }
        }
        ,
        Penality {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getPenality();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setPenality((Number)value);
            }
        }
        ,
        PenalityApprovalFlag {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getPenalityApprovalFlag();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setPenalityApprovalFlag((String)value);
            }
        }
        ,
        RentRefund {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getRentRefund();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setRentRefund((Number)value);
            }
        }
        ,
        RentRefundApprovalFlag {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getRentRefundApprovalFlag();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setRentRefundApprovalFlag((String)value);
            }
        }
        ,
        RefundType {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getRefundType();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setRefundType((String)value);
            }
        }
        ,
        PropertyId {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getPropertyId();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setPropertyId((Number)value);
            }
        }
        ,
        IsDeletedFlag {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getIsDeletedFlag();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setIsDeletedFlag((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAttribute11();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAttribute12();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAttribute13();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAttribute14();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getAttribute15();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        ExtAttributeCategory {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getExtAttributeCategory();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setExtAttributeCategory((String)value);
            }
        }
        ,
        ExtAttribute1 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getExtAttribute1();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setExtAttribute1((String)value);
            }
        }
        ,
        ExtAttribute2 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getExtAttribute2();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setExtAttribute2((String)value);
            }
        }
        ,
        ExtAttribute3 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getExtAttribute3();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setExtAttribute3((String)value);
            }
        }
        ,
        ExtAttribute4 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getExtAttribute4();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setExtAttribute4((String)value);
            }
        }
        ,
        ExtAttribute5 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getExtAttribute5();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setExtAttribute5((String)value);
            }
        }
        ,
        ExtAttribute6 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getExtAttribute6();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setExtAttribute6((String)value);
            }
        }
        ,
        ExtAttribute7 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getExtAttribute7();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setExtAttribute7((String)value);
            }
        }
        ,
        ExtAttribute8 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getExtAttribute8();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setExtAttribute8((String)value);
            }
        }
        ,
        ExtAttribute9 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getExtAttribute9();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setExtAttribute9((String)value);
            }
        }
        ,
        ExtAttribute10 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getExtAttribute10();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setExtAttribute10((String)value);
            }
        }
        ,
        ExtAttribute11 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getExtAttribute11();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setExtAttribute11((String)value);
            }
        }
        ,
        ExtAttribute12 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getExtAttribute12();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setExtAttribute12((String)value);
            }
        }
        ,
        ExtAttribute13 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getExtAttribute13();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setExtAttribute13((String)value);
            }
        }
        ,
        ExtAttribute14 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getExtAttribute14();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setExtAttribute14((String)value);
            }
        }
        ,
        ExtAttribute15 {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getExtAttribute15();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setExtAttribute15((String)value);
            }
        }
        ,
        ParentLeaseId {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getParentLeaseId();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setParentLeaseId((Number)value);
            }
        }
        ,
        LeaseVersion {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getLeaseVersion();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setLeaseVersion((String)value);
            }
        }
        ,
        VendorId {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getVendorId();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setVendorId((Number)value);
            }
        }
        ,
        VendorContactId {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getVendorContactId();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setVendorContactId((Number)value);
            }
        }
        ,
        RenewedContractsHistory {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getRenewedContractsHistory();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setRenewedContractsHistory((String)value);
            }
        }
        ,
        VendorSiteId {
            public Object get(MARealEstateleaseEOImpl obj) {
                return obj.getVendorSiteId();
            }

            public void put(MARealEstateleaseEOImpl obj, Object value) {
                obj.setVendorSiteId((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(MARealEstateleaseEOImpl object);

        public abstract void put(MARealEstateleaseEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int LEASEID = AttributesEnum.LeaseId.index();
    public static final int LEASESEGMENT = AttributesEnum.LeaseSegment.index();
    public static final int SUBJECT = AttributesEnum.Subject.index();
    public static final int LEASERNAME = AttributesEnum.LeaserName.index();
    public static final int LEASERADDRESS = AttributesEnum.LeaserAddress.index();
    public static final int CONTACTPERSON = AttributesEnum.ContactPerson.index();
    public static final int CONTACTPHONENUMBER = AttributesEnum.ContactPhoneNumber.index();
    public static final int CONTACTEMAIL = AttributesEnum.ContactEmail.index();
    public static final int OPPORTUNITYID = AttributesEnum.OpportunityId.index();
    public static final int LEASESTATUS = AttributesEnum.LeaseStatus.index();
    public static final int LEASETYPE = AttributesEnum.LeaseType.index();
    public static final int TREINNELPERCENTAGE = AttributesEnum.TreinnelPercentage.index();
    public static final int PARENTLEASE = AttributesEnum.ParentLease.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int BOOKINGEXPIRINGON = AttributesEnum.BookingExpiringOn.index();
    public static final int INCREASE = AttributesEnum.Increase.index();
    public static final int ITERATIONMONTHS = AttributesEnum.IterationMonths.index();
    public static final int AUTOCALCULATEFLAG = AttributesEnum.AutoCalculateFlag.index();
    public static final int TENUREMONTHS = AttributesEnum.TenureMonths.index();
    public static final int LEASETERMSCONDITIONS = AttributesEnum.LeaseTermsConditions.index();
    public static final int BILLINGFREQUENCY = AttributesEnum.BillingFrequency.index();
    public static final int WATER = AttributesEnum.Water.index();
    public static final int ELECTRICITY = AttributesEnum.Electricity.index();
    public static final int SANITATION = AttributesEnum.Sanitation.index();
    public static final int BADGE = AttributesEnum.Badge.index();
    public static final int DISCOUNT = AttributesEnum.Discount.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int RENTAMOUNT = AttributesEnum.RentAmount.index();
    public static final int ADHOCKCHARGES = AttributesEnum.AdhockCharges.index();
    public static final int GROSSRENTAMOUNT = AttributesEnum.GrossRentAmount.index();
    public static final int DISCOUNTAMOUNT = AttributesEnum.DiscountAmount.index();
    public static final int NETAMOUNT = AttributesEnum.NetAmount.index();
    public static final int RENEWALNOTICESENT = AttributesEnum.RenewalNoticeSent.index();
    public static final int RECEIVEDCONFIRMATIONDATE = AttributesEnum.ReceivedConfirmationDate.index();
    public static final int CUSTOMERRESPONSE = AttributesEnum.CustomerResponse.index();
    public static final int PROPOSEDYEARLYRENT = AttributesEnum.ProposedYearlyRent.index();
    public static final int VACANTDATE = AttributesEnum.VacantDate.index();
    public static final int EXTENDEDDATE = AttributesEnum.ExtendedDate.index();
    public static final int TERMINATIONNOTICESENT = AttributesEnum.TerminationNoticeSent.index();
    public static final int TERMINATIONDATE = AttributesEnum.TerminationDate.index();
    public static final int TERMINATIONREASON = AttributesEnum.TerminationReason.index();
    public static final int TERMINATIONREASONDETAILS = AttributesEnum.TerminationReasonDetails.index();
    public static final int ADMINCHARGES = AttributesEnum.AdminCharges.index();
    public static final int ADMINCHARGESAPPROVALFLAG = AttributesEnum.AdminChargesApprovalFlag.index();
    public static final int PENALITY = AttributesEnum.Penality.index();
    public static final int PENALITYAPPROVALFLAG = AttributesEnum.PenalityApprovalFlag.index();
    public static final int RENTREFUND = AttributesEnum.RentRefund.index();
    public static final int RENTREFUNDAPPROVALFLAG = AttributesEnum.RentRefundApprovalFlag.index();
    public static final int REFUNDTYPE = AttributesEnum.RefundType.index();
    public static final int PROPERTYID = AttributesEnum.PropertyId.index();
    public static final int ISDELETEDFLAG = AttributesEnum.IsDeletedFlag.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int EXTATTRIBUTECATEGORY = AttributesEnum.ExtAttributeCategory.index();
    public static final int EXTATTRIBUTE1 = AttributesEnum.ExtAttribute1.index();
    public static final int EXTATTRIBUTE2 = AttributesEnum.ExtAttribute2.index();
    public static final int EXTATTRIBUTE3 = AttributesEnum.ExtAttribute3.index();
    public static final int EXTATTRIBUTE4 = AttributesEnum.ExtAttribute4.index();
    public static final int EXTATTRIBUTE5 = AttributesEnum.ExtAttribute5.index();
    public static final int EXTATTRIBUTE6 = AttributesEnum.ExtAttribute6.index();
    public static final int EXTATTRIBUTE7 = AttributesEnum.ExtAttribute7.index();
    public static final int EXTATTRIBUTE8 = AttributesEnum.ExtAttribute8.index();
    public static final int EXTATTRIBUTE9 = AttributesEnum.ExtAttribute9.index();
    public static final int EXTATTRIBUTE10 = AttributesEnum.ExtAttribute10.index();
    public static final int EXTATTRIBUTE11 = AttributesEnum.ExtAttribute11.index();
    public static final int EXTATTRIBUTE12 = AttributesEnum.ExtAttribute12.index();
    public static final int EXTATTRIBUTE13 = AttributesEnum.ExtAttribute13.index();
    public static final int EXTATTRIBUTE14 = AttributesEnum.ExtAttribute14.index();
    public static final int EXTATTRIBUTE15 = AttributesEnum.ExtAttribute15.index();
    public static final int PARENTLEASEID = AttributesEnum.ParentLeaseId.index();
    public static final int LEASEVERSION = AttributesEnum.LeaseVersion.index();
    public static final int VENDORID = AttributesEnum.VendorId.index();
    public static final int VENDORCONTACTID = AttributesEnum.VendorContactId.index();
    public static final int RENEWEDCONTRACTSHISTORY = AttributesEnum.RenewedContractsHistory.index();
    public static final int VENDORSITEID = AttributesEnum.VendorSiteId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MARealEstateleaseEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("ma.oracle.apps.cx.realestate.lease.entities.MARealEstateleaseEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for LeaseId, using the alias name LeaseId.
     * @return the LeaseId
     */
    public Number getLeaseId() {
        return (Number)getAttributeInternal(LEASEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LeaseId.
     * @param value value to set the LeaseId
     */
    public void setLeaseId(Number value) {
        setAttributeInternal(LEASEID, value);
    }

    /**
     * Gets the attribute value for LeaseSegment, using the alias name LeaseSegment.
     * @return the LeaseSegment
     */
    public String getLeaseSegment() {
        return (String)getAttributeInternal(LEASESEGMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for LeaseSegment.
     * @param value value to set the LeaseSegment
     */
    public void setLeaseSegment(String value) {
        setAttributeInternal(LEASESEGMENT, value);
    }

    /**
     * Gets the attribute value for Subject, using the alias name Subject.
     * @return the Subject
     */
    public String getSubject() {
        return (String)getAttributeInternal(SUBJECT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Subject.
     * @param value value to set the Subject
     */
    public void setSubject(String value) {
        setAttributeInternal(SUBJECT, value);
    }

    /**
     * Gets the attribute value for LeaserName, using the alias name LeaserName.
     * @return the LeaserName
     */
    public String getLeaserName() {
        return (String)getAttributeInternal(LEASERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for LeaserName.
     * @param value value to set the LeaserName
     */
    public void setLeaserName(String value) {
        setAttributeInternal(LEASERNAME, value);
    }

    /**
     * Gets the attribute value for LeaserAddress, using the alias name LeaserAddress.
     * @return the LeaserAddress
     */
    public String getLeaserAddress() {
        return (String)getAttributeInternal(LEASERADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for LeaserAddress.
     * @param value value to set the LeaserAddress
     */
    public void setLeaserAddress(String value) {
        setAttributeInternal(LEASERADDRESS, value);
    }

    /**
     * Gets the attribute value for ContactPerson, using the alias name ContactPerson.
     * @return the ContactPerson
     */
    public String getContactPerson() {
        return (String)getAttributeInternal(CONTACTPERSON);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContactPerson.
     * @param value value to set the ContactPerson
     */
    public void setContactPerson(String value) {
        setAttributeInternal(CONTACTPERSON, value);
    }

    /**
     * Gets the attribute value for ContactPhoneNumber, using the alias name ContactPhoneNumber.
     * @return the ContactPhoneNumber
     */
    public String getContactPhoneNumber() {
        return (String)getAttributeInternal(CONTACTPHONENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContactPhoneNumber.
     * @param value value to set the ContactPhoneNumber
     */
    public void setContactPhoneNumber(String value) {
        setAttributeInternal(CONTACTPHONENUMBER, value);
    }

    /**
     * Gets the attribute value for ContactEmail, using the alias name ContactEmail.
     * @return the ContactEmail
     */
    public String getContactEmail() {
        return (String)getAttributeInternal(CONTACTEMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContactEmail.
     * @param value value to set the ContactEmail
     */
    public void setContactEmail(String value) {
        setAttributeInternal(CONTACTEMAIL, value);
    }

    /**
     * Gets the attribute value for OpportunityId, using the alias name OpportunityId.
     * @return the OpportunityId
     */
    public Number getOpportunityId() {
        return (Number)getAttributeInternal(OPPORTUNITYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OpportunityId.
     * @param value value to set the OpportunityId
     */
    public void setOpportunityId(Number value) {
        setAttributeInternal(OPPORTUNITYID, value);
    }

    /**
     * Gets the attribute value for LeaseStatus, using the alias name LeaseStatus.
     * @return the LeaseStatus
     */
    public String getLeaseStatus() {
        return (String)getAttributeInternal(LEASESTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for LeaseStatus.
     * @param value value to set the LeaseStatus
     */
    public void setLeaseStatus(String value) {
        setAttributeInternal(LEASESTATUS, value);
    }

    /**
     * Gets the attribute value for LeaseType, using the alias name LeaseType.
     * @return the LeaseType
     */
    public String getLeaseType() {
        return (String)getAttributeInternal(LEASETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LeaseType.
     * @param value value to set the LeaseType
     */
    public void setLeaseType(String value) {
        setAttributeInternal(LEASETYPE, value);
    }

    /**
     * Gets the attribute value for TreinnelPercentage, using the alias name TreinnelPercentage.
     * @return the TreinnelPercentage
     */
    public Number getTreinnelPercentage() {
        return (Number)getAttributeInternal(TREINNELPERCENTAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TreinnelPercentage.
     * @param value value to set the TreinnelPercentage
     */
    public void setTreinnelPercentage(Number value) {
        setAttributeInternal(TREINNELPERCENTAGE, value);
    }

    /**
     * Gets the attribute value for ParentLease, using the alias name ParentLease.
     * @return the ParentLease
     */
    public String getParentLease() {
        return (String)getAttributeInternal(PARENTLEASE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParentLease.
     * @param value value to set the ParentLease
     */
    public void setParentLease(String value) {
        setAttributeInternal(PARENTLEASE, value);
    }

    /**
     * Gets the attribute value for StartDate, using the alias name StartDate.
     * @return the StartDate
     */
    public Date getStartDate() {
        return (Date)getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StartDate.
     * @param value value to set the StartDate
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for EndDate, using the alias name EndDate.
     * @return the EndDate
     */
    public Date getEndDate() {
        return (Date)getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndDate.
     * @param value value to set the EndDate
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for BookingExpiringOn, using the alias name BookingExpiringOn.
     * @return the BookingExpiringOn
     */
    public Date getBookingExpiringOn() {
        return (Date)getAttributeInternal(BOOKINGEXPIRINGON);
    }

    /**
     * Sets <code>value</code> as the attribute value for BookingExpiringOn.
     * @param value value to set the BookingExpiringOn
     */
    public void setBookingExpiringOn(Date value) {
        setAttributeInternal(BOOKINGEXPIRINGON, value);
    }

    /**
     * Gets the attribute value for Increase, using the alias name Increase.
     * @return the Increase
     */
    public String getIncrease() {
        return (String)getAttributeInternal(INCREASE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Increase.
     * @param value value to set the Increase
     */
    public void setIncrease(String value) {
        setAttributeInternal(INCREASE, value);
    }

    /**
     * Gets the attribute value for IterationMonths, using the alias name IterationMonths.
     * @return the IterationMonths
     */
    public Number getIterationMonths() {
        return (Number)getAttributeInternal(ITERATIONMONTHS);
    }

    /**
     * Sets <code>value</code> as the attribute value for IterationMonths.
     * @param value value to set the IterationMonths
     */
    public void setIterationMonths(Number value) {
        setAttributeInternal(ITERATIONMONTHS, value);
    }

    /**
     * Gets the attribute value for AutoCalculateFlag, using the alias name AutoCalculateFlag.
     * @return the AutoCalculateFlag
     */
    public String getAutoCalculateFlag() {
        return (String)getAttributeInternal(AUTOCALCULATEFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for AutoCalculateFlag.
     * @param value value to set the AutoCalculateFlag
     */
    public void setAutoCalculateFlag(String value) {
        setAttributeInternal(AUTOCALCULATEFLAG, value);
    }

    /**
     * Gets the attribute value for TenureMonths, using the alias name TenureMonths.
     * @return the TenureMonths
     */
    public String getTenureMonths() {
        return (String)getAttributeInternal(TENUREMONTHS);
    }

    /**
     * Sets <code>value</code> as the attribute value for TenureMonths.
     * @param value value to set the TenureMonths
     */
    public void setTenureMonths(String value) {
        setAttributeInternal(TENUREMONTHS, value);
    }

    /**
     * Gets the attribute value for LeaseTermsConditions, using the alias name LeaseTermsConditions.
     * @return the LeaseTermsConditions
     */
    public String getLeaseTermsConditions() {
        return (String)getAttributeInternal(LEASETERMSCONDITIONS);
    }

    /**
     * Sets <code>value</code> as the attribute value for LeaseTermsConditions.
     * @param value value to set the LeaseTermsConditions
     */
    public void setLeaseTermsConditions(String value) {
        setAttributeInternal(LEASETERMSCONDITIONS, value);
    }

    /**
     * Gets the attribute value for BillingFrequency, using the alias name BillingFrequency.
     * @return the BillingFrequency
     */
    public String getBillingFrequency() {
        return (String)getAttributeInternal(BILLINGFREQUENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillingFrequency.
     * @param value value to set the BillingFrequency
     */
    public void setBillingFrequency(String value) {
        setAttributeInternal(BILLINGFREQUENCY, value);
    }

    /**
     * Gets the attribute value for Water, using the alias name Water.
     * @return the Water
     */
    public Number getWater() {
        return (Number)getAttributeInternal(WATER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Water.
     * @param value value to set the Water
     */
    public void setWater(Number value) {
        setAttributeInternal(WATER, value);
    }

    /**
     * Gets the attribute value for Electricity, using the alias name Electricity.
     * @return the Electricity
     */
    public Number getElectricity() {
        return (Number)getAttributeInternal(ELECTRICITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Electricity.
     * @param value value to set the Electricity
     */
    public void setElectricity(Number value) {
        setAttributeInternal(ELECTRICITY, value);
    }

    /**
     * Gets the attribute value for Sanitation, using the alias name Sanitation.
     * @return the Sanitation
     */
    public Number getSanitation() {
        return (Number)getAttributeInternal(SANITATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Sanitation.
     * @param value value to set the Sanitation
     */
    public void setSanitation(Number value) {
        setAttributeInternal(SANITATION, value);
    }

    /**
     * Gets the attribute value for Badge, using the alias name Badge.
     * @return the Badge
     */
    public Number getBadge() {
        return (Number)getAttributeInternal(BADGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Badge.
     * @param value value to set the Badge
     */
    public void setBadge(Number value) {
        setAttributeInternal(BADGE, value);
    }

    /**
     * Gets the attribute value for Discount, using the alias name Discount.
     * @return the Discount
     */
    public Number getDiscount() {
        return (Number)getAttributeInternal(DISCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Discount.
     * @param value value to set the Discount
     */
    public void setDiscount(Number value) {
        setAttributeInternal(DISCOUNT, value);
    }

    /**
     * Gets the attribute value for Currency, using the alias name Currency.
     * @return the Currency
     */
    public String getCurrency() {
        return (String)getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Currency.
     * @param value value to set the Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for RentAmount, using the alias name RentAmount.
     * @return the RentAmount
     */
    public Number getRentAmount() {
        return (Number)getAttributeInternal(RENTAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for RentAmount.
     * @param value value to set the RentAmount
     */
    public void setRentAmount(Number value) {
        setAttributeInternal(RENTAMOUNT, value);
    }

    /**
     * Gets the attribute value for AdhockCharges, using the alias name AdhockCharges.
     * @return the AdhockCharges
     */
    public Number getAdhockCharges() {
        return (Number)getAttributeInternal(ADHOCKCHARGES);
    }

    /**
     * Sets <code>value</code> as the attribute value for AdhockCharges.
     * @param value value to set the AdhockCharges
     */
    public void setAdhockCharges(Number value) {
        setAttributeInternal(ADHOCKCHARGES, value);
    }

    /**
     * Gets the attribute value for GrossRentAmount, using the alias name GrossRentAmount.
     * @return the GrossRentAmount
     */
    public Number getGrossRentAmount() {
        return (Number)getAttributeInternal(GROSSRENTAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrossRentAmount.
     * @param value value to set the GrossRentAmount
     */
    public void setGrossRentAmount(Number value) {
        setAttributeInternal(GROSSRENTAMOUNT, value);
    }

    /**
     * Gets the attribute value for DiscountAmount, using the alias name DiscountAmount.
     * @return the DiscountAmount
     */
    public Number getDiscountAmount() {
        return (Number)getAttributeInternal(DISCOUNTAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DiscountAmount.
     * @param value value to set the DiscountAmount
     */
    public void setDiscountAmount(Number value) {
        setAttributeInternal(DISCOUNTAMOUNT, value);
    }

    /**
     * Gets the attribute value for NetAmount, using the alias name NetAmount.
     * @return the NetAmount
     */
    public Number getNetAmount() {
        return (Number)getAttributeInternal(NETAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for NetAmount.
     * @param value value to set the NetAmount
     */
    public void setNetAmount(Number value) {
        setAttributeInternal(NETAMOUNT, value);
    }

    /**
     * Gets the attribute value for RenewalNoticeSent, using the alias name RenewalNoticeSent.
     * @return the RenewalNoticeSent
     */
    public Date getRenewalNoticeSent() {
        return (Date)getAttributeInternal(RENEWALNOTICESENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for RenewalNoticeSent.
     * @param value value to set the RenewalNoticeSent
     */
    public void setRenewalNoticeSent(Date value) {
        setAttributeInternal(RENEWALNOTICESENT, value);
    }

    /**
     * Gets the attribute value for ReceivedConfirmationDate, using the alias name ReceivedConfirmationDate.
     * @return the ReceivedConfirmationDate
     */
    public Date getReceivedConfirmationDate() {
        return (Date)getAttributeInternal(RECEIVEDCONFIRMATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReceivedConfirmationDate.
     * @param value value to set the ReceivedConfirmationDate
     */
    public void setReceivedConfirmationDate(Date value) {
        setAttributeInternal(RECEIVEDCONFIRMATIONDATE, value);
    }

    /**
     * Gets the attribute value for CustomerResponse, using the alias name CustomerResponse.
     * @return the CustomerResponse
     */
    public String getCustomerResponse() {
        return (String)getAttributeInternal(CUSTOMERRESPONSE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerResponse.
     * @param value value to set the CustomerResponse
     */
    public void setCustomerResponse(String value) {
        setAttributeInternal(CUSTOMERRESPONSE, value);
    }

    /**
     * Gets the attribute value for ProposedYearlyRent, using the alias name ProposedYearlyRent.
     * @return the ProposedYearlyRent
     */
    public String getProposedYearlyRent() {
        return (String)getAttributeInternal(PROPOSEDYEARLYRENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProposedYearlyRent.
     * @param value value to set the ProposedYearlyRent
     */
    public void setProposedYearlyRent(String value) {
        setAttributeInternal(PROPOSEDYEARLYRENT, value);
    }

    /**
     * Gets the attribute value for VacantDate, using the alias name VacantDate.
     * @return the VacantDate
     */
    public Date getVacantDate() {
        return (Date)getAttributeInternal(VACANTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VacantDate.
     * @param value value to set the VacantDate
     */
    public void setVacantDate(Date value) {
        setAttributeInternal(VACANTDATE, value);
    }

    /**
     * Gets the attribute value for ExtendedDate, using the alias name ExtendedDate.
     * @return the ExtendedDate
     */
    public Date getExtendedDate() {
        return (Date)getAttributeInternal(EXTENDEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtendedDate.
     * @param value value to set the ExtendedDate
     */
    public void setExtendedDate(Date value) {
        setAttributeInternal(EXTENDEDDATE, value);
    }

    /**
     * Gets the attribute value for TerminationNoticeSent, using the alias name TerminationNoticeSent.
     * @return the TerminationNoticeSent
     */
    public Date getTerminationNoticeSent() {
        return (Date)getAttributeInternal(TERMINATIONNOTICESENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TerminationNoticeSent.
     * @param value value to set the TerminationNoticeSent
     */
    public void setTerminationNoticeSent(Date value) {
        setAttributeInternal(TERMINATIONNOTICESENT, value);
    }

    /**
     * Gets the attribute value for TerminationDate, using the alias name TerminationDate.
     * @return the TerminationDate
     */
    public Date getTerminationDate() {
        return (Date)getAttributeInternal(TERMINATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TerminationDate.
     * @param value value to set the TerminationDate
     */
    public void setTerminationDate(Date value) {
        setAttributeInternal(TERMINATIONDATE, value);
    }

    /**
     * Gets the attribute value for TerminationReason, using the alias name TerminationReason.
     * @return the TerminationReason
     */
    public String getTerminationReason() {
        return (String)getAttributeInternal(TERMINATIONREASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for TerminationReason.
     * @param value value to set the TerminationReason
     */
    public void setTerminationReason(String value) {
        setAttributeInternal(TERMINATIONREASON, value);
    }

    /**
     * Gets the attribute value for TerminationReasonDetails, using the alias name TerminationReasonDetails.
     * @return the TerminationReasonDetails
     */
    public String getTerminationReasonDetails() {
        return (String)getAttributeInternal(TERMINATIONREASONDETAILS);
    }

    /**
     * Sets <code>value</code> as the attribute value for TerminationReasonDetails.
     * @param value value to set the TerminationReasonDetails
     */
    public void setTerminationReasonDetails(String value) {
        setAttributeInternal(TERMINATIONREASONDETAILS, value);
    }

    /**
     * Gets the attribute value for AdminCharges, using the alias name AdminCharges.
     * @return the AdminCharges
     */
    public Number getAdminCharges() {
        return (Number)getAttributeInternal(ADMINCHARGES);
    }

    /**
     * Sets <code>value</code> as the attribute value for AdminCharges.
     * @param value value to set the AdminCharges
     */
    public void setAdminCharges(Number value) {
        setAttributeInternal(ADMINCHARGES, value);
    }

    /**
     * Gets the attribute value for AdminChargesApprovalFlag, using the alias name AdminChargesApprovalFlag.
     * @return the AdminChargesApprovalFlag
     */
    public String getAdminChargesApprovalFlag() {
        return (String)getAttributeInternal(ADMINCHARGESAPPROVALFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for AdminChargesApprovalFlag.
     * @param value value to set the AdminChargesApprovalFlag
     */
    public void setAdminChargesApprovalFlag(String value) {
        setAttributeInternal(ADMINCHARGESAPPROVALFLAG, value);
    }

    /**
     * Gets the attribute value for Penality, using the alias name Penality.
     * @return the Penality
     */
    public Number getPenality() {
        return (Number)getAttributeInternal(PENALITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Penality.
     * @param value value to set the Penality
     */
    public void setPenality(Number value) {
        setAttributeInternal(PENALITY, value);
    }

    /**
     * Gets the attribute value for PenalityApprovalFlag, using the alias name PenalityApprovalFlag.
     * @return the PenalityApprovalFlag
     */
    public String getPenalityApprovalFlag() {
        return (String)getAttributeInternal(PENALITYAPPROVALFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for PenalityApprovalFlag.
     * @param value value to set the PenalityApprovalFlag
     */
    public void setPenalityApprovalFlag(String value) {
        setAttributeInternal(PENALITYAPPROVALFLAG, value);
    }

    /**
     * Gets the attribute value for RentRefund, using the alias name RentRefund.
     * @return the RentRefund
     */
    public Number getRentRefund() {
        return (Number)getAttributeInternal(RENTREFUND);
    }

    /**
     * Sets <code>value</code> as the attribute value for RentRefund.
     * @param value value to set the RentRefund
     */
    public void setRentRefund(Number value) {
        setAttributeInternal(RENTREFUND, value);
    }

    /**
     * Gets the attribute value for RentRefundApprovalFlag, using the alias name RentRefundApprovalFlag.
     * @return the RentRefundApprovalFlag
     */
    public String getRentRefundApprovalFlag() {
        return (String)getAttributeInternal(RENTREFUNDAPPROVALFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for RentRefundApprovalFlag.
     * @param value value to set the RentRefundApprovalFlag
     */
    public void setRentRefundApprovalFlag(String value) {
        setAttributeInternal(RENTREFUNDAPPROVALFLAG, value);
    }

    /**
     * Gets the attribute value for RefundType, using the alias name RefundType.
     * @return the RefundType
     */
    public String getRefundType() {
        return (String)getAttributeInternal(REFUNDTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RefundType.
     * @param value value to set the RefundType
     */
    public void setRefundType(String value) {
        setAttributeInternal(REFUNDTYPE, value);
    }

    /**
     * Gets the attribute value for PropertyId, using the alias name PropertyId.
     * @return the PropertyId
     */
    public Number getPropertyId() {
        return (Number)getAttributeInternal(PROPERTYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PropertyId.
     * @param value value to set the PropertyId
     */
    public void setPropertyId(Number value) {
        setAttributeInternal(PROPERTYID, value);
    }

    /**
     * Gets the attribute value for IsDeletedFlag, using the alias name IsDeletedFlag.
     * @return the IsDeletedFlag
     */
    public String getIsDeletedFlag() {
        return (String)getAttributeInternal(ISDELETEDFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsDeletedFlag.
     * @param value value to set the IsDeletedFlag
     */
    public void setIsDeletedFlag(String value) {
        setAttributeInternal(ISDELETEDFLAG, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for AttributeCategory, using the alias name AttributeCategory.
     * @return the AttributeCategory
     */
    public String getAttributeCategory() {
        return (String)getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeCategory.
     * @param value value to set the AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for ExtAttributeCategory, using the alias name ExtAttributeCategory.
     * @return the ExtAttributeCategory
     */
    public String getExtAttributeCategory() {
        return (String)getAttributeInternal(EXTATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttributeCategory.
     * @param value value to set the ExtAttributeCategory
     */
    public void setExtAttributeCategory(String value) {
        setAttributeInternal(EXTATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for ExtAttribute1, using the alias name ExtAttribute1.
     * @return the ExtAttribute1
     */
    public String getExtAttribute1() {
        return (String)getAttributeInternal(EXTATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute1.
     * @param value value to set the ExtAttribute1
     */
    public void setExtAttribute1(String value) {
        setAttributeInternal(EXTATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ExtAttribute2, using the alias name ExtAttribute2.
     * @return the ExtAttribute2
     */
    public String getExtAttribute2() {
        return (String)getAttributeInternal(EXTATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute2.
     * @param value value to set the ExtAttribute2
     */
    public void setExtAttribute2(String value) {
        setAttributeInternal(EXTATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ExtAttribute3, using the alias name ExtAttribute3.
     * @return the ExtAttribute3
     */
    public String getExtAttribute3() {
        return (String)getAttributeInternal(EXTATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute3.
     * @param value value to set the ExtAttribute3
     */
    public void setExtAttribute3(String value) {
        setAttributeInternal(EXTATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ExtAttribute4, using the alias name ExtAttribute4.
     * @return the ExtAttribute4
     */
    public String getExtAttribute4() {
        return (String)getAttributeInternal(EXTATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute4.
     * @param value value to set the ExtAttribute4
     */
    public void setExtAttribute4(String value) {
        setAttributeInternal(EXTATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ExtAttribute5, using the alias name ExtAttribute5.
     * @return the ExtAttribute5
     */
    public String getExtAttribute5() {
        return (String)getAttributeInternal(EXTATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute5.
     * @param value value to set the ExtAttribute5
     */
    public void setExtAttribute5(String value) {
        setAttributeInternal(EXTATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ExtAttribute6, using the alias name ExtAttribute6.
     * @return the ExtAttribute6
     */
    public String getExtAttribute6() {
        return (String)getAttributeInternal(EXTATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute6.
     * @param value value to set the ExtAttribute6
     */
    public void setExtAttribute6(String value) {
        setAttributeInternal(EXTATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ExtAttribute7, using the alias name ExtAttribute7.
     * @return the ExtAttribute7
     */
    public String getExtAttribute7() {
        return (String)getAttributeInternal(EXTATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute7.
     * @param value value to set the ExtAttribute7
     */
    public void setExtAttribute7(String value) {
        setAttributeInternal(EXTATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ExtAttribute8, using the alias name ExtAttribute8.
     * @return the ExtAttribute8
     */
    public String getExtAttribute8() {
        return (String)getAttributeInternal(EXTATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute8.
     * @param value value to set the ExtAttribute8
     */
    public void setExtAttribute8(String value) {
        setAttributeInternal(EXTATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ExtAttribute9, using the alias name ExtAttribute9.
     * @return the ExtAttribute9
     */
    public String getExtAttribute9() {
        return (String)getAttributeInternal(EXTATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute9.
     * @param value value to set the ExtAttribute9
     */
    public void setExtAttribute9(String value) {
        setAttributeInternal(EXTATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ExtAttribute10, using the alias name ExtAttribute10.
     * @return the ExtAttribute10
     */
    public String getExtAttribute10() {
        return (String)getAttributeInternal(EXTATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute10.
     * @param value value to set the ExtAttribute10
     */
    public void setExtAttribute10(String value) {
        setAttributeInternal(EXTATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ExtAttribute11, using the alias name ExtAttribute11.
     * @return the ExtAttribute11
     */
    public String getExtAttribute11() {
        return (String)getAttributeInternal(EXTATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute11.
     * @param value value to set the ExtAttribute11
     */
    public void setExtAttribute11(String value) {
        setAttributeInternal(EXTATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ExtAttribute12, using the alias name ExtAttribute12.
     * @return the ExtAttribute12
     */
    public String getExtAttribute12() {
        return (String)getAttributeInternal(EXTATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute12.
     * @param value value to set the ExtAttribute12
     */
    public void setExtAttribute12(String value) {
        setAttributeInternal(EXTATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ExtAttribute13, using the alias name ExtAttribute13.
     * @return the ExtAttribute13
     */
    public String getExtAttribute13() {
        return (String)getAttributeInternal(EXTATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute13.
     * @param value value to set the ExtAttribute13
     */
    public void setExtAttribute13(String value) {
        setAttributeInternal(EXTATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ExtAttribute14, using the alias name ExtAttribute14.
     * @return the ExtAttribute14
     */
    public String getExtAttribute14() {
        return (String)getAttributeInternal(EXTATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute14.
     * @param value value to set the ExtAttribute14
     */
    public void setExtAttribute14(String value) {
        setAttributeInternal(EXTATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ExtAttribute15, using the alias name ExtAttribute15.
     * @return the ExtAttribute15
     */
    public String getExtAttribute15() {
        return (String)getAttributeInternal(EXTATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute15.
     * @param value value to set the ExtAttribute15
     */
    public void setExtAttribute15(String value) {
        setAttributeInternal(EXTATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for ParentLeaseId, using the alias name ParentLeaseId.
     * @return the ParentLeaseId
     */
    public Number getParentLeaseId() {
        return (Number)getAttributeInternal(PARENTLEASEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParentLeaseId.
     * @param value value to set the ParentLeaseId
     */
    public void setParentLeaseId(Number value) {
        setAttributeInternal(PARENTLEASEID, value);
    }

    /**
     * Gets the attribute value for LeaseVersion, using the alias name LeaseVersion.
     * @return the LeaseVersion
     */
    public String getLeaseVersion() {
        return (String)getAttributeInternal(LEASEVERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for LeaseVersion.
     * @param value value to set the LeaseVersion
     */
    public void setLeaseVersion(String value) {
        setAttributeInternal(LEASEVERSION, value);
    }

    /**
     * Gets the attribute value for VendorId, using the alias name VendorId.
     * @return the VendorId
     */
    public Number getVendorId() {
        return (Number)getAttributeInternal(VENDORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for VendorId.
     * @param value value to set the VendorId
     */
    public void setVendorId(Number value) {
        setAttributeInternal(VENDORID, value);
    }

    /**
     * Gets the attribute value for VendorContactId, using the alias name VendorContactId.
     * @return the VendorContactId
     */
    public Number getVendorContactId() {
        return (Number)getAttributeInternal(VENDORCONTACTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for VendorContactId.
     * @param value value to set the VendorContactId
     */
    public void setVendorContactId(Number value) {
        setAttributeInternal(VENDORCONTACTID, value);
    }

    /**
     * Gets the attribute value for RenewedContractsHistory, using the alias name RenewedContractsHistory.
     * @return the RenewedContractsHistory
     */
    public String getRenewedContractsHistory() {
        return (String)getAttributeInternal(RENEWEDCONTRACTSHISTORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for RenewedContractsHistory.
     * @param value value to set the RenewedContractsHistory
     */
    public void setRenewedContractsHistory(String value) {
        setAttributeInternal(RENEWEDCONTRACTSHISTORY, value);
    }

    /**
     * Gets the attribute value for VendorSiteId, using the alias name VendorSiteId.
     * @return the VendorSiteId
     */
    public Number getVendorSiteId() {
        return (Number)getAttributeInternal(VENDORSITEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for VendorSiteId.
     * @param value value to set the VendorSiteId
     */
    public void setVendorSiteId(Number value) {
        setAttributeInternal(VENDORSITEID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param leaseId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number leaseId) {
        return new Key(new Object[]{leaseId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seq =
            new SequenceImpl("XXMA.XXMA_REAL_ESTATE_LEASE_SEQ", getDBTransaction());
        setLeaseId(seq.getSequenceNumber());
        setCreatedBy(new Number(1));
        setLastUpdatedBy(new Number(1));
        setLastUpdateLogin(new Number(1));
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
