package ma.oracle.apps.cx.realestate.lease.modules.client;

import ma.oracle.apps.cx.realestate.lease.modules.common.MARealEstateLeaseAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 04 15:20:32 EEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MARealEstateLeaseAMClient extends ApplicationModuleImpl implements MARealEstateLeaseAM {
    /**
     * This is the default constructor (do not remove).
     */
    public MARealEstateLeaseAMClient() {
    }

    public void initOppLeasePropertyQuery() {
        Object _ret =
            this.riInvokeExportedMethod(this,"initOppLeasePropertyQuery",null,null);
        return;
    }


    public void createOppLeasePropertyRow(Number propertyId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createOppLeasePropertyRow",new String [] {"oracle.jbo.domain.Number"},new Object[] {propertyId});
        return;
    }


    public void initLeaseQuery(Number leaseId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"initLeaseQuery",new String [] {"oracle.jbo.domain.Number"},new Object[] {leaseId});
        return;
    }

    public Number createLeasePropertyRow(Number propertyId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createLeasePropertyRow",new String [] {"oracle.jbo.domain.Number"},new Object[] {propertyId});
        return (Number)_ret;
    }

    public void initOppLeasePropertyQuery(Number opportunityId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"initOppLeasePropertyQuery",new String [] {"oracle.jbo.domain.Number"},new Object[] {opportunityId});
        return;
    }

    public void createOppLeasePropertyRow(Number propertyId,
                                          Number opportunityId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createOppLeasePropertyRow",new String [] {"oracle.jbo.domain.Number","oracle.jbo.domain.Number"},new Object[] {propertyId, opportunityId});
        return;
    }

    public Number createLeaseFromOpportunity(Number opportunityId,
                                             String leaseSubject) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createLeaseFromOpportunity",new String [] {"oracle.jbo.domain.Number","java.lang.String"},new Object[] {opportunityId, leaseSubject});
        return (Number)_ret;
    }
}
