package ma.oracle.apps.cx.realestate.lease.views;

import ma.oracle.apps.cx.realestate.lease.entities.MARSLeasePaymentsEOImpl;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 01 17:14:14 EEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MARSLeasePaymentsVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PaymentId {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getPaymentId();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setPaymentId((Number)value);
            }
        }
        ,
        LeaseId {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getLeaseId();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setLeaseId((Number)value);
            }
        }
        ,
        PropertyId {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getPropertyId();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setPropertyId((Number)value);
            }
        }
        ,
        PaymentType {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getPaymentType();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setPaymentType((String)value);
            }
        }
        ,
        PaymentNumber {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getPaymentNumber();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setPaymentNumber((String)value);
            }
        }
        ,
        Amount {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getAmount();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAmount((Number)value);
            }
        }
        ,
        DueDate {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getDueDate();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setDueDate((Date)value);
            }
        }
        ,
        PaymentDate {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getPaymentDate();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setPaymentDate((Date)value);
            }
        }
        ,
        RemitToBank {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getRemitToBank();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setRemitToBank((String)value);
            }
        }
        ,
        PaymentStatus {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getPaymentStatus();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setPaymentStatus((String)value);
            }
        }
        ,
        Remarks {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getRemarks();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        ContractRefrence {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getContractRefrence();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setContractRefrence((String)value);
            }
        }
        ,
        IsDeletedFlag {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getIsDeletedFlag();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setIsDeletedFlag((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        ExtAttributeCategory {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getExtAttributeCategory();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setExtAttributeCategory((String)value);
            }
        }
        ,
        ExtAttribute1 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getExtAttribute1();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setExtAttribute1((String)value);
            }
        }
        ,
        ExtAttribute2 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getExtAttribute2();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setExtAttribute2((String)value);
            }
        }
        ,
        ExtAttribute3 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getExtAttribute3();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setExtAttribute3((String)value);
            }
        }
        ,
        ExtAttribute4 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getExtAttribute4();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setExtAttribute4((String)value);
            }
        }
        ,
        ExtAttribute5 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getExtAttribute5();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setExtAttribute5((String)value);
            }
        }
        ,
        ExtAttribute6 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getExtAttribute6();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setExtAttribute6((String)value);
            }
        }
        ,
        ExtAttribute7 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getExtAttribute7();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setExtAttribute7((String)value);
            }
        }
        ,
        ExtAttribute8 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getExtAttribute8();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setExtAttribute8((String)value);
            }
        }
        ,
        ExtAttribute9 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getExtAttribute9();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setExtAttribute9((String)value);
            }
        }
        ,
        ExtAttribute10 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getExtAttribute10();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setExtAttribute10((String)value);
            }
        }
        ,
        ExtAttribute11 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getExtAttribute11();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setExtAttribute11((String)value);
            }
        }
        ,
        ExtAttribute12 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getExtAttribute12();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setExtAttribute12((String)value);
            }
        }
        ,
        ExtAttribute13 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getExtAttribute13();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setExtAttribute13((String)value);
            }
        }
        ,
        ExtAttribute14 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getExtAttribute14();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setExtAttribute14((String)value);
            }
        }
        ,
        ExtAttribute15 {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getExtAttribute15();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setExtAttribute15((String)value);
            }
        }
        ,
        MARealEstateleaseVO {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getMARealEstateleaseVO();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MAPaymentTypesVVO {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getMAPaymentTypesVVO();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MARemitToBankVVO {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getMARemitToBankVVO();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MAPaymentStatusVVO {
            public Object get(MARSLeasePaymentsVORowImpl obj) {
                return obj.getMAPaymentStatusVVO();
            }

            public void put(MARSLeasePaymentsVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(MARSLeasePaymentsVORowImpl object);

        public abstract void put(MARSLeasePaymentsVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PAYMENTID = AttributesEnum.PaymentId.index();
    public static final int LEASEID = AttributesEnum.LeaseId.index();
    public static final int PROPERTYID = AttributesEnum.PropertyId.index();
    public static final int PAYMENTTYPE = AttributesEnum.PaymentType.index();
    public static final int PAYMENTNUMBER = AttributesEnum.PaymentNumber.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int DUEDATE = AttributesEnum.DueDate.index();
    public static final int PAYMENTDATE = AttributesEnum.PaymentDate.index();
    public static final int REMITTOBANK = AttributesEnum.RemitToBank.index();
    public static final int PAYMENTSTATUS = AttributesEnum.PaymentStatus.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int CONTRACTREFRENCE = AttributesEnum.ContractRefrence.index();
    public static final int ISDELETEDFLAG = AttributesEnum.IsDeletedFlag.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int EXTATTRIBUTECATEGORY = AttributesEnum.ExtAttributeCategory.index();
    public static final int EXTATTRIBUTE1 = AttributesEnum.ExtAttribute1.index();
    public static final int EXTATTRIBUTE2 = AttributesEnum.ExtAttribute2.index();
    public static final int EXTATTRIBUTE3 = AttributesEnum.ExtAttribute3.index();
    public static final int EXTATTRIBUTE4 = AttributesEnum.ExtAttribute4.index();
    public static final int EXTATTRIBUTE5 = AttributesEnum.ExtAttribute5.index();
    public static final int EXTATTRIBUTE6 = AttributesEnum.ExtAttribute6.index();
    public static final int EXTATTRIBUTE7 = AttributesEnum.ExtAttribute7.index();
    public static final int EXTATTRIBUTE8 = AttributesEnum.ExtAttribute8.index();
    public static final int EXTATTRIBUTE9 = AttributesEnum.ExtAttribute9.index();
    public static final int EXTATTRIBUTE10 = AttributesEnum.ExtAttribute10.index();
    public static final int EXTATTRIBUTE11 = AttributesEnum.ExtAttribute11.index();
    public static final int EXTATTRIBUTE12 = AttributesEnum.ExtAttribute12.index();
    public static final int EXTATTRIBUTE13 = AttributesEnum.ExtAttribute13.index();
    public static final int EXTATTRIBUTE14 = AttributesEnum.ExtAttribute14.index();
    public static final int EXTATTRIBUTE15 = AttributesEnum.ExtAttribute15.index();
    public static final int MAREALESTATELEASEVO = AttributesEnum.MARealEstateleaseVO.index();
    public static final int MAPAYMENTTYPESVVO = AttributesEnum.MAPaymentTypesVVO.index();
    public static final int MAREMITTOBANKVVO = AttributesEnum.MARemitToBankVVO.index();
    public static final int MAPAYMENTSTATUSVVO = AttributesEnum.MAPaymentStatusVVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MARSLeasePaymentsVORowImpl() {
    }

    /**
     * Gets MARSLeasePaymentsEO entity object.
     * @return the MARSLeasePaymentsEO
     */
    public MARSLeasePaymentsEOImpl getMARSLeasePaymentsEO() {
        return (MARSLeasePaymentsEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for PAYMENT_ID using the alias name PaymentId.
     * @return the PAYMENT_ID
     */
    public Number getPaymentId() {
        return (Number) getAttributeInternal(PAYMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_ID using the alias name PaymentId.
     * @param value value to set the PAYMENT_ID
     */
    public void setPaymentId(Number value) {
        setAttributeInternal(PAYMENTID, value);
    }

    /**
     * Gets the attribute value for LEASE_ID using the alias name LeaseId.
     * @return the LEASE_ID
     */
    public Number getLeaseId() {
        return (Number) getAttributeInternal(LEASEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LEASE_ID using the alias name LeaseId.
     * @param value value to set the LEASE_ID
     */
    public void setLeaseId(Number value) {
        setAttributeInternal(LEASEID, value);
    }

    /**
     * Gets the attribute value for PROPERTY_ID using the alias name PropertyId.
     * @return the PROPERTY_ID
     */
    public Number getPropertyId() {
        return (Number) getAttributeInternal(PROPERTYID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPERTY_ID using the alias name PropertyId.
     * @param value value to set the PROPERTY_ID
     */
    public void setPropertyId(Number value) {
        setAttributeInternal(PROPERTYID, value);
    }

    /**
     * Gets the attribute value for PAYMENT_TYPE using the alias name PaymentType.
     * @return the PAYMENT_TYPE
     */
    public String getPaymentType() {
        return (String) getAttributeInternal(PAYMENTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_TYPE using the alias name PaymentType.
     * @param value value to set the PAYMENT_TYPE
     */
    public void setPaymentType(String value) {
        setAttributeInternal(PAYMENTTYPE, value);
    }

    /**
     * Gets the attribute value for PAYMENT_NUMBER using the alias name PaymentNumber.
     * @return the PAYMENT_NUMBER
     */
    public String getPaymentNumber() {
        return (String) getAttributeInternal(PAYMENTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_NUMBER using the alias name PaymentNumber.
     * @param value value to set the PAYMENT_NUMBER
     */
    public void setPaymentNumber(String value) {
        setAttributeInternal(PAYMENTNUMBER, value);
    }

    /**
     * Gets the attribute value for AMOUNT using the alias name Amount.
     * @return the AMOUNT
     */
    public Number getAmount() {
        return (Number) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for AMOUNT using the alias name Amount.
     * @param value value to set the AMOUNT
     */
    public void setAmount(Number value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for DUE_DATE using the alias name DueDate.
     * @return the DUE_DATE
     */
    public Date getDueDate() {
        return (Date) getAttributeInternal(DUEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DUE_DATE using the alias name DueDate.
     * @param value value to set the DUE_DATE
     */
    public void setDueDate(Date value) {
        setAttributeInternal(DUEDATE, value);
    }

    /**
     * Gets the attribute value for PAYMENT_DATE using the alias name PaymentDate.
     * @return the PAYMENT_DATE
     */
    public Date getPaymentDate() {
        return (Date) getAttributeInternal(PAYMENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_DATE using the alias name PaymentDate.
     * @param value value to set the PAYMENT_DATE
     */
    public void setPaymentDate(Date value) {
        setAttributeInternal(PAYMENTDATE, value);
    }

    /**
     * Gets the attribute value for REMIT_TO_BANK using the alias name RemitToBank.
     * @return the REMIT_TO_BANK
     */
    public String getRemitToBank() {
        return (String) getAttributeInternal(REMITTOBANK);
    }

    /**
     * Sets <code>value</code> as attribute value for REMIT_TO_BANK using the alias name RemitToBank.
     * @param value value to set the REMIT_TO_BANK
     */
    public void setRemitToBank(String value) {
        setAttributeInternal(REMITTOBANK, value);
    }

    /**
     * Gets the attribute value for PAYMENT_STATUS using the alias name PaymentStatus.
     * @return the PAYMENT_STATUS
     */
    public String getPaymentStatus() {
        return (String) getAttributeInternal(PAYMENTSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_STATUS using the alias name PaymentStatus.
     * @param value value to set the PAYMENT_STATUS
     */
    public void setPaymentStatus(String value) {
        setAttributeInternal(PAYMENTSTATUS, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for CONTRACT_REFRENCE using the alias name ContractRefrence.
     * @return the CONTRACT_REFRENCE
     */
    public String getContractRefrence() {
        return (String) getAttributeInternal(CONTRACTREFRENCE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_REFRENCE using the alias name ContractRefrence.
     * @param value value to set the CONTRACT_REFRENCE
     */
    public void setContractRefrence(String value) {
        setAttributeInternal(CONTRACTREFRENCE, value);
    }

    /**
     * Gets the attribute value for IS_DELETED_FLAG using the alias name IsDeletedFlag.
     * @return the IS_DELETED_FLAG
     */
    public String getIsDeletedFlag() {
        return (String) getAttributeInternal(ISDELETEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_DELETED_FLAG using the alias name IsDeletedFlag.
     * @param value value to set the IS_DELETED_FLAG
     */
    public void setIsDeletedFlag(String value) {
        setAttributeInternal(ISDELETEDFLAG, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for EXT_ATTRIBUTE_CATEGORY using the alias name ExtAttributeCategory.
     * @return the EXT_ATTRIBUTE_CATEGORY
     */
    public String getExtAttributeCategory() {
        return (String) getAttributeInternal(EXTATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for EXT_ATTRIBUTE_CATEGORY using the alias name ExtAttributeCategory.
     * @param value value to set the EXT_ATTRIBUTE_CATEGORY
     */
    public void setExtAttributeCategory(String value) {
        setAttributeInternal(EXTATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for EXT_ATTRIBUTE1 using the alias name ExtAttribute1.
     * @return the EXT_ATTRIBUTE1
     */
    public String getExtAttribute1() {
        return (String) getAttributeInternal(EXTATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for EXT_ATTRIBUTE1 using the alias name ExtAttribute1.
     * @param value value to set the EXT_ATTRIBUTE1
     */
    public void setExtAttribute1(String value) {
        setAttributeInternal(EXTATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for EXT_ATTRIBUTE2 using the alias name ExtAttribute2.
     * @return the EXT_ATTRIBUTE2
     */
    public String getExtAttribute2() {
        return (String) getAttributeInternal(EXTATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for EXT_ATTRIBUTE2 using the alias name ExtAttribute2.
     * @param value value to set the EXT_ATTRIBUTE2
     */
    public void setExtAttribute2(String value) {
        setAttributeInternal(EXTATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for EXT_ATTRIBUTE3 using the alias name ExtAttribute3.
     * @return the EXT_ATTRIBUTE3
     */
    public String getExtAttribute3() {
        return (String) getAttributeInternal(EXTATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for EXT_ATTRIBUTE3 using the alias name ExtAttribute3.
     * @param value value to set the EXT_ATTRIBUTE3
     */
    public void setExtAttribute3(String value) {
        setAttributeInternal(EXTATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for EXT_ATTRIBUTE4 using the alias name ExtAttribute4.
     * @return the EXT_ATTRIBUTE4
     */
    public String getExtAttribute4() {
        return (String) getAttributeInternal(EXTATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for EXT_ATTRIBUTE4 using the alias name ExtAttribute4.
     * @param value value to set the EXT_ATTRIBUTE4
     */
    public void setExtAttribute4(String value) {
        setAttributeInternal(EXTATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for EXT_ATTRIBUTE5 using the alias name ExtAttribute5.
     * @return the EXT_ATTRIBUTE5
     */
    public String getExtAttribute5() {
        return (String) getAttributeInternal(EXTATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for EXT_ATTRIBUTE5 using the alias name ExtAttribute5.
     * @param value value to set the EXT_ATTRIBUTE5
     */
    public void setExtAttribute5(String value) {
        setAttributeInternal(EXTATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for EXT_ATTRIBUTE6 using the alias name ExtAttribute6.
     * @return the EXT_ATTRIBUTE6
     */
    public String getExtAttribute6() {
        return (String) getAttributeInternal(EXTATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for EXT_ATTRIBUTE6 using the alias name ExtAttribute6.
     * @param value value to set the EXT_ATTRIBUTE6
     */
    public void setExtAttribute6(String value) {
        setAttributeInternal(EXTATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for EXT_ATTRIBUTE7 using the alias name ExtAttribute7.
     * @return the EXT_ATTRIBUTE7
     */
    public String getExtAttribute7() {
        return (String) getAttributeInternal(EXTATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for EXT_ATTRIBUTE7 using the alias name ExtAttribute7.
     * @param value value to set the EXT_ATTRIBUTE7
     */
    public void setExtAttribute7(String value) {
        setAttributeInternal(EXTATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for EXT_ATTRIBUTE8 using the alias name ExtAttribute8.
     * @return the EXT_ATTRIBUTE8
     */
    public String getExtAttribute8() {
        return (String) getAttributeInternal(EXTATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for EXT_ATTRIBUTE8 using the alias name ExtAttribute8.
     * @param value value to set the EXT_ATTRIBUTE8
     */
    public void setExtAttribute8(String value) {
        setAttributeInternal(EXTATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for EXT_ATTRIBUTE9 using the alias name ExtAttribute9.
     * @return the EXT_ATTRIBUTE9
     */
    public String getExtAttribute9() {
        return (String) getAttributeInternal(EXTATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for EXT_ATTRIBUTE9 using the alias name ExtAttribute9.
     * @param value value to set the EXT_ATTRIBUTE9
     */
    public void setExtAttribute9(String value) {
        setAttributeInternal(EXTATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for EXT_ATTRIBUTE10 using the alias name ExtAttribute10.
     * @return the EXT_ATTRIBUTE10
     */
    public String getExtAttribute10() {
        return (String) getAttributeInternal(EXTATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for EXT_ATTRIBUTE10 using the alias name ExtAttribute10.
     * @param value value to set the EXT_ATTRIBUTE10
     */
    public void setExtAttribute10(String value) {
        setAttributeInternal(EXTATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for EXT_ATTRIBUTE11 using the alias name ExtAttribute11.
     * @return the EXT_ATTRIBUTE11
     */
    public String getExtAttribute11() {
        return (String) getAttributeInternal(EXTATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for EXT_ATTRIBUTE11 using the alias name ExtAttribute11.
     * @param value value to set the EXT_ATTRIBUTE11
     */
    public void setExtAttribute11(String value) {
        setAttributeInternal(EXTATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for EXT_ATTRIBUTE12 using the alias name ExtAttribute12.
     * @return the EXT_ATTRIBUTE12
     */
    public String getExtAttribute12() {
        return (String) getAttributeInternal(EXTATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for EXT_ATTRIBUTE12 using the alias name ExtAttribute12.
     * @param value value to set the EXT_ATTRIBUTE12
     */
    public void setExtAttribute12(String value) {
        setAttributeInternal(EXTATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for EXT_ATTRIBUTE13 using the alias name ExtAttribute13.
     * @return the EXT_ATTRIBUTE13
     */
    public String getExtAttribute13() {
        return (String) getAttributeInternal(EXTATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for EXT_ATTRIBUTE13 using the alias name ExtAttribute13.
     * @param value value to set the EXT_ATTRIBUTE13
     */
    public void setExtAttribute13(String value) {
        setAttributeInternal(EXTATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for EXT_ATTRIBUTE14 using the alias name ExtAttribute14.
     * @return the EXT_ATTRIBUTE14
     */
    public String getExtAttribute14() {
        return (String) getAttributeInternal(EXTATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for EXT_ATTRIBUTE14 using the alias name ExtAttribute14.
     * @param value value to set the EXT_ATTRIBUTE14
     */
    public void setExtAttribute14(String value) {
        setAttributeInternal(EXTATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for EXT_ATTRIBUTE15 using the alias name ExtAttribute15.
     * @return the EXT_ATTRIBUTE15
     */
    public String getExtAttribute15() {
        return (String) getAttributeInternal(EXTATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for EXT_ATTRIBUTE15 using the alias name ExtAttribute15.
     * @param value value to set the EXT_ATTRIBUTE15
     */
    public void setExtAttribute15(String value) {
        setAttributeInternal(EXTATTRIBUTE15, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link MARealEstateleaseVO.
     */
    public Row getMARealEstateleaseVO() {
        return (Row)getAttributeInternal(MAREALESTATELEASEVO);
    }

    /**
     * Sets the master-detail link MARealEstateleaseVO between this object and <code>value</code>.
     */
    public void setMARealEstateleaseVO(Row value) {
        setAttributeInternal(MAREALESTATELEASEVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MAPaymentTypesVVO.
     */
    public RowSet getMAPaymentTypesVVO() {
        return (RowSet)getAttributeInternal(MAPAYMENTTYPESVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MARemitToBankVVO.
     */
    public RowSet getMARemitToBankVVO() {
        return (RowSet)getAttributeInternal(MAREMITTOBANKVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MAPaymentStatusVVO.
     */
    public RowSet getMAPaymentStatusVVO() {
        return (RowSet)getAttributeInternal(MAPAYMENTSTATUSVVO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
