package ma.oracle.apps.cx.realestate.lease.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 23 21:06:54 EEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MARSLeaseChargesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MARSLeaseChargesVOImpl() {
    }
}
