package ma.oracle.apps.cx.realestate.contract.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 16 10:53:47 EET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MARealEstatePropertyVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MARealEstatePropertyVOImpl() {
    }
}

