package ma.oracle.apps.cx.realestate.building.views;

import java.sql.Date;

import ma.oracle.apps.cx.realestate.building.entities.MARealEstateBuildingEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 10 10:36:32 EET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MARSBuildingSearchVORowImpl extends ViewRowImpl {


    public static final int ENTITY_MAREALESTATEBUILDINGEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BuildingId {
            public Object get(MARSBuildingSearchVORowImpl obj) {
                return obj.getBuildingId();
            }

            public void put(MARSBuildingSearchVORowImpl obj, Object value) {
                obj.setBuildingId((Number) value);
            }
        }
        ,
        BuildingName {
            public Object get(MARSBuildingSearchVORowImpl obj) {
                return obj.getBuildingName();
            }

            public void put(MARSBuildingSearchVORowImpl obj, Object value) {
                obj.setBuildingName((String) value);
            }
        }
        ,
        ProjectId {
            public Object get(MARSBuildingSearchVORowImpl obj) {
                return obj.getProjectId();
            }

            public void put(MARSBuildingSearchVORowImpl obj, Object value) {
                obj.setProjectId((Number) value);
            }
        }
        ,
        StartServiceDate {
            public Object get(MARSBuildingSearchVORowImpl obj) {
                return obj.getStartServiceDate();
            }

            public void put(MARSBuildingSearchVORowImpl obj, Object value) {
                obj.setStartServiceDate((Date) value);
            }
        }
        ,
        EndServiceDate {
            public Object get(MARSBuildingSearchVORowImpl obj) {
                return obj.getEndServiceDate();
            }

            public void put(MARSBuildingSearchVORowImpl obj, Object value) {
                obj.setEndServiceDate((Date) value);
            }
        }
        ,
        BuildingLocation {
            public Object get(MARSBuildingSearchVORowImpl obj) {
                return obj.getBuildingLocation();
            }

            public void put(MARSBuildingSearchVORowImpl obj, Object value) {
                obj.setBuildingLocation((String) value);
            }
        }
        ,
        BuildingType {
            public Object get(MARSBuildingSearchVORowImpl obj) {
                return obj.getBuildingType();
            }

            public void put(MARSBuildingSearchVORowImpl obj, Object value) {
                obj.setBuildingType((String) value);
            }
        }
        ,
        NoOfFloors {
            public Object get(MARSBuildingSearchVORowImpl obj) {
                return obj.getNoOfFloors();
            }

            public void put(MARSBuildingSearchVORowImpl obj, Object value) {
                obj.setNoOfFloors((Number) value);
            }
        }
        ,
        AvailableForRentFlag {
            public Object get(MARSBuildingSearchVORowImpl obj) {
                return obj.getAvailableForRentFlag();
            }

            public void put(MARSBuildingSearchVORowImpl obj, Object value) {
                obj.setAvailableForRentFlag((String) value);
            }
        }
        ,
        Status {
            public Object get(MARSBuildingSearchVORowImpl obj) {
                return obj.getStatus();
            }

            public void put(MARSBuildingSearchVORowImpl obj, Object value) {
                obj.setStatus((String) value);
            }
        }
        ,
        WestSide {
            public Object get(MARSBuildingSearchVORowImpl obj) {
                return obj.getWestSide();
            }

            public void put(MARSBuildingSearchVORowImpl obj, Object value) {
                obj.setWestSide((String) value);
            }
        }
        ,
        NorthSide {
            public Object get(MARSBuildingSearchVORowImpl obj) {
                return obj.getNorthSide();
            }

            public void put(MARSBuildingSearchVORowImpl obj, Object value) {
                obj.setNorthSide((String) value);
            }
        }
        ,
        MARealEstateBuildingVO1 {
            public Object get(MARSBuildingSearchVORowImpl obj) {
                return obj.getMARealEstateBuildingVO1();
            }

            public void put(MARSBuildingSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MAParentBuildingTypeVVO1 {
            public Object get(MARSBuildingSearchVORowImpl obj) {
                return obj.getMAParentBuildingTypeVVO1();
            }

            public void put(MARSBuildingSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public abstract Object get(MARSBuildingSearchVORowImpl object);

        public abstract void put(MARSBuildingSearchVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BUILDINGID = AttributesEnum.BuildingId.index();
    public static final int BUILDINGNAME = AttributesEnum.BuildingName.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int STARTSERVICEDATE = AttributesEnum.StartServiceDate.index();
    public static final int ENDSERVICEDATE = AttributesEnum.EndServiceDate.index();
    public static final int BUILDINGLOCATION = AttributesEnum.BuildingLocation.index();
    public static final int BUILDINGTYPE = AttributesEnum.BuildingType.index();
    public static final int NOOFFLOORS = AttributesEnum.NoOfFloors.index();
    public static final int AVAILABLEFORRENTFLAG = AttributesEnum.AvailableForRentFlag.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int WESTSIDE = AttributesEnum.WestSide.index();
    public static final int NORTHSIDE = AttributesEnum.NorthSide.index();
    public static final int MAREALESTATEBUILDINGVO1 = AttributesEnum.MARealEstateBuildingVO1.index();
    public static final int MAPARENTBUILDINGTYPEVVO1 = AttributesEnum.MAParentBuildingTypeVVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MARSBuildingSearchVORowImpl() {
    }

    /**
     * Gets MARealEstateBuildingEO entity object.
     * @return the MARealEstateBuildingEO
     */
    public MARealEstateBuildingEOImpl getMARealEstateBuildingEO() {
        return (MARealEstateBuildingEOImpl) getEntity(ENTITY_MAREALESTATEBUILDINGEO);
    }

    /**
     * Gets the attribute value for BUILDING_ID using the alias name BuildingId.
     * @return the BUILDING_ID
     */
    public Number getBuildingId() {
        return (Number) getAttributeInternal(BUILDINGID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUILDING_ID using the alias name BuildingId.
     * @param value value to set the BUILDING_ID
     */
    public void setBuildingId(Number value) {
        setAttributeInternal(BUILDINGID, value);
    }

    /**
     * Gets the attribute value for BUILDING_NAME using the alias name BuildingName.
     * @return the BUILDING_NAME
     */
    public String getBuildingName() {
        return (String) getAttributeInternal(BUILDINGNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for BUILDING_NAME using the alias name BuildingName.
     * @param value value to set the BUILDING_NAME
     */
    public void setBuildingName(String value) {
        setAttributeInternal(BUILDINGNAME, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public Number getProjectId() {
        return (Number) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(Number value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for START_SERVICE_DATE using the alias name StartServiceDate.
     * @return the START_SERVICE_DATE
     */
    public Date getStartServiceDate() {
        return (Date) getAttributeInternal(STARTSERVICEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_SERVICE_DATE using the alias name StartServiceDate.
     * @param value value to set the START_SERVICE_DATE
     */
    public void setStartServiceDate(Date value) {
        setAttributeInternal(STARTSERVICEDATE, value);
    }

    /**
     * Gets the attribute value for END_SERVICE_DATE using the alias name EndServiceDate.
     * @return the END_SERVICE_DATE
     */
    public Date getEndServiceDate() {
        return (Date) getAttributeInternal(ENDSERVICEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_SERVICE_DATE using the alias name EndServiceDate.
     * @param value value to set the END_SERVICE_DATE
     */
    public void setEndServiceDate(Date value) {
        setAttributeInternal(ENDSERVICEDATE, value);
    }

    /**
     * Gets the attribute value for BUILDING_LOCATION using the alias name BuildingLocation.
     * @return the BUILDING_LOCATION
     */
    public String getBuildingLocation() {
        return (String) getAttributeInternal(BUILDINGLOCATION);
    }

    /**
     * Sets <code>value</code> as attribute value for BUILDING_LOCATION using the alias name BuildingLocation.
     * @param value value to set the BUILDING_LOCATION
     */
    public void setBuildingLocation(String value) {
        setAttributeInternal(BUILDINGLOCATION, value);
    }

    /**
     * Gets the attribute value for BUILDING_TYPE using the alias name BuildingType.
     * @return the BUILDING_TYPE
     */
    public String getBuildingType() {
        return (String) getAttributeInternal(BUILDINGTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for BUILDING_TYPE using the alias name BuildingType.
     * @param value value to set the BUILDING_TYPE
     */
    public void setBuildingType(String value) {
        setAttributeInternal(BUILDINGTYPE, value);
    }

    /**
     * Gets the attribute value for NO_OF_FLOORS using the alias name NoOfFloors.
     * @return the NO_OF_FLOORS
     */
    public Number getNoOfFloors() {
        return (Number) getAttributeInternal(NOOFFLOORS);
    }

    /**
     * Sets <code>value</code> as attribute value for NO_OF_FLOORS using the alias name NoOfFloors.
     * @param value value to set the NO_OF_FLOORS
     */
    public void setNoOfFloors(Number value) {
        setAttributeInternal(NOOFFLOORS, value);
    }

    /**
     * Gets the attribute value for AVAILABLE_FOR_RENT_FLAG using the alias name AvailableForRentFlag.
     * @return the AVAILABLE_FOR_RENT_FLAG
     */
    public String getAvailableForRentFlag() {
        return (String) getAttributeInternal(AVAILABLEFORRENTFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for AVAILABLE_FOR_RENT_FLAG using the alias name AvailableForRentFlag.
     * @param value value to set the AVAILABLE_FOR_RENT_FLAG
     */
    public void setAvailableForRentFlag(String value) {
        setAttributeInternal(AVAILABLEFORRENTFLAG, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for WEST_SIDE using the alias name WestSide.
     * @return the WEST_SIDE
     */
    public String getWestSide() {
        return (String) getAttributeInternal(WESTSIDE);
    }

    /**
     * Sets <code>value</code> as attribute value for WEST_SIDE using the alias name WestSide.
     * @param value value to set the WEST_SIDE
     */
    public void setWestSide(String value) {
        setAttributeInternal(WESTSIDE, value);
    }

    /**
     * Gets the attribute value for NORTH_SIDE using the alias name NorthSide.
     * @return the NORTH_SIDE
     */
    public String getNorthSide() {
        return (String) getAttributeInternal(NORTHSIDE);
    }

    /**
     * Sets <code>value</code> as attribute value for NORTH_SIDE using the alias name NorthSide.
     * @param value value to set the NORTH_SIDE
     */
    public void setNorthSide(String value) {
        setAttributeInternal(NORTHSIDE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MARealEstateBuildingVO1.
     */
    public RowSet getMARealEstateBuildingVO1() {
        return (RowSet) getAttributeInternal(MAREALESTATEBUILDINGVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MAParentBuildingTypeVVO1.
     */
    public RowSet getMAParentBuildingTypeVVO1() {
        return (RowSet) getAttributeInternal(MAPARENTBUILDINGTYPEVVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

