package ma.oracle.apps.cx.realestate.project.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 17 14:23:07 EET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MAProjectPhasesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MAProjectPhasesVOImpl() {
    }
}

