package ma.oracle.apps.cx.realestate.lease.modules.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 04 15:20:32 EEST 2018
// ---------------------------------------------------------------------
public interface MARealEstateLeaseAM extends ApplicationModule {

    void initLeaseQuery(Number leaseId);


    Number createLeasePropertyRow(Number propertyId);

    void initOppLeasePropertyQuery(Number opportunityId);

    void createOppLeasePropertyRow(Number propertyId, Number opportunityId);

    Number createLeaseFromOpportunity(Number opportunityId,
                                      String leaseSubject);
}
