package ma.oracle.apps.cx.realestate.building.entities;

import java.sql.Date;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 13 13:35:17 EET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MARsBuildingTypesEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BuildingTypeId {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getBuildingTypeId();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setBuildingTypeId((Number) value);
            }
        }
        ,
        ParentBuildingTypeId {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getParentBuildingTypeId();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setParentBuildingTypeId((Number) value);
            }
        }
        ,
        BuildingTypeName {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getBuildingTypeName();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setBuildingTypeName((String) value);
            }
        }
        ,
        CreatedBy {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setCreatedBy((Number) value);
            }
        }
        ,
        CreationDate {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setCreationDate((Date) value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number) value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date) value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setLastUpdateLogin((Number) value);
            }
        }
        ,
        IntAttributeCategory {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getIntAttributeCategory();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setIntAttributeCategory((String) value);
            }
        }
        ,
        IntAttribute1 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getIntAttribute1();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setIntAttribute1((String) value);
            }
        }
        ,
        IntAttribute2 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getIntAttribute2();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setIntAttribute2((String) value);
            }
        }
        ,
        IntAttribute3 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getIntAttribute3();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setIntAttribute3((String) value);
            }
        }
        ,
        IntAttribute4 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getIntAttribute4();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setIntAttribute4((String) value);
            }
        }
        ,
        IntAttribute5 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getIntAttribute5();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setIntAttribute5((String) value);
            }
        }
        ,
        IntAttribute6 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getIntAttribute6();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setIntAttribute6((String) value);
            }
        }
        ,
        IntAttribute7 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getIntAttribute7();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setIntAttribute7((String) value);
            }
        }
        ,
        IntAttribute8 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getIntAttribute8();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setIntAttribute8((String) value);
            }
        }
        ,
        IntAttribute9 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getIntAttribute9();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setIntAttribute9((String) value);
            }
        }
        ,
        IntAttribute10 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getIntAttribute10();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setIntAttribute10((String) value);
            }
        }
        ,
        IntAttribute11 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getIntAttribute11();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setIntAttribute11((String) value);
            }
        }
        ,
        IntAttribute12 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getIntAttribute12();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setIntAttribute12((String) value);
            }
        }
        ,
        IntAttribute13 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getIntAttribute13();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setIntAttribute13((String) value);
            }
        }
        ,
        IntAttribute14 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getIntAttribute14();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setIntAttribute14((String) value);
            }
        }
        ,
        IntAttribute15 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getIntAttribute15();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setIntAttribute15((String) value);
            }
        }
        ,
        ExtAttributeCategory {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getExtAttributeCategory();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setExtAttributeCategory((String) value);
            }
        }
        ,
        ExtAttribute1 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getExtAttribute1();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setExtAttribute1((String) value);
            }
        }
        ,
        ExtAttribute2 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getExtAttribute2();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setExtAttribute2((String) value);
            }
        }
        ,
        ExtAttribute3 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getExtAttribute3();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setExtAttribute3((String) value);
            }
        }
        ,
        ExtAttribute4 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getExtAttribute4();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setExtAttribute4((String) value);
            }
        }
        ,
        ExtAttribute5 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getExtAttribute5();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setExtAttribute5((String) value);
            }
        }
        ,
        ExtAttribute6 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getExtAttribute6();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setExtAttribute6((String) value);
            }
        }
        ,
        ExtAttribute7 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getExtAttribute7();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setExtAttribute7((String) value);
            }
        }
        ,
        ExtAttribute8 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getExtAttribute8();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setExtAttribute8((String) value);
            }
        }
        ,
        ExtAttribute9 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getExtAttribute9();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setExtAttribute9((String) value);
            }
        }
        ,
        ExtAttribute10 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getExtAttribute10();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setExtAttribute10((String) value);
            }
        }
        ,
        ExtAttribute11 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getExtAttribute11();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setExtAttribute11((String) value);
            }
        }
        ,
        ExtAttribute12 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getExtAttribute12();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setExtAttribute12((String) value);
            }
        }
        ,
        ExtAttribute13 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getExtAttribute13();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setExtAttribute13((String) value);
            }
        }
        ,
        ExtAttribute14 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getExtAttribute14();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setExtAttribute14((String) value);
            }
        }
        ,
        ExtAttribute15 {
            public Object get(MARsBuildingTypesEOImpl obj) {
                return obj.getExtAttribute15();
            }

            public void put(MARsBuildingTypesEOImpl obj, Object value) {
                obj.setExtAttribute15((String) value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(MARsBuildingTypesEOImpl object);

        public abstract void put(MARsBuildingTypesEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BUILDINGTYPEID = AttributesEnum.BuildingTypeId.index();
    public static final int PARENTBUILDINGTYPEID = AttributesEnum.ParentBuildingTypeId.index();
    public static final int BUILDINGTYPENAME = AttributesEnum.BuildingTypeName.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int INTATTRIBUTECATEGORY = AttributesEnum.IntAttributeCategory.index();
    public static final int INTATTRIBUTE1 = AttributesEnum.IntAttribute1.index();
    public static final int INTATTRIBUTE2 = AttributesEnum.IntAttribute2.index();
    public static final int INTATTRIBUTE3 = AttributesEnum.IntAttribute3.index();
    public static final int INTATTRIBUTE4 = AttributesEnum.IntAttribute4.index();
    public static final int INTATTRIBUTE5 = AttributesEnum.IntAttribute5.index();
    public static final int INTATTRIBUTE6 = AttributesEnum.IntAttribute6.index();
    public static final int INTATTRIBUTE7 = AttributesEnum.IntAttribute7.index();
    public static final int INTATTRIBUTE8 = AttributesEnum.IntAttribute8.index();
    public static final int INTATTRIBUTE9 = AttributesEnum.IntAttribute9.index();
    public static final int INTATTRIBUTE10 = AttributesEnum.IntAttribute10.index();
    public static final int INTATTRIBUTE11 = AttributesEnum.IntAttribute11.index();
    public static final int INTATTRIBUTE12 = AttributesEnum.IntAttribute12.index();
    public static final int INTATTRIBUTE13 = AttributesEnum.IntAttribute13.index();
    public static final int INTATTRIBUTE14 = AttributesEnum.IntAttribute14.index();
    public static final int INTATTRIBUTE15 = AttributesEnum.IntAttribute15.index();
    public static final int EXTATTRIBUTECATEGORY = AttributesEnum.ExtAttributeCategory.index();
    public static final int EXTATTRIBUTE1 = AttributesEnum.ExtAttribute1.index();
    public static final int EXTATTRIBUTE2 = AttributesEnum.ExtAttribute2.index();
    public static final int EXTATTRIBUTE3 = AttributesEnum.ExtAttribute3.index();
    public static final int EXTATTRIBUTE4 = AttributesEnum.ExtAttribute4.index();
    public static final int EXTATTRIBUTE5 = AttributesEnum.ExtAttribute5.index();
    public static final int EXTATTRIBUTE6 = AttributesEnum.ExtAttribute6.index();
    public static final int EXTATTRIBUTE7 = AttributesEnum.ExtAttribute7.index();
    public static final int EXTATTRIBUTE8 = AttributesEnum.ExtAttribute8.index();
    public static final int EXTATTRIBUTE9 = AttributesEnum.ExtAttribute9.index();
    public static final int EXTATTRIBUTE10 = AttributesEnum.ExtAttribute10.index();
    public static final int EXTATTRIBUTE11 = AttributesEnum.ExtAttribute11.index();
    public static final int EXTATTRIBUTE12 = AttributesEnum.ExtAttribute12.index();
    public static final int EXTATTRIBUTE13 = AttributesEnum.ExtAttribute13.index();
    public static final int EXTATTRIBUTE14 = AttributesEnum.ExtAttribute14.index();
    public static final int EXTATTRIBUTE15 = AttributesEnum.ExtAttribute15.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MARsBuildingTypesEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("ma.oracle.apps.cx.realestate.building.entities.MARsBuildingTypesEO");
    }


    /**
     * Gets the attribute value for BuildingTypeId, using the alias name BuildingTypeId.
     * @return the value of BuildingTypeId
     */
    public Number getBuildingTypeId() {
        return (Number) getAttributeInternal(BUILDINGTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuildingTypeId.
     * @param value value to set the BuildingTypeId
     */
    public void setBuildingTypeId(Number value) {
        setAttributeInternal(BUILDINGTYPEID, value);
    }

    /**
     * Gets the attribute value for ParentBuildingTypeId, using the alias name ParentBuildingTypeId.
     * @return the value of ParentBuildingTypeId
     */
    public oracle.jbo.domain.Number getParentBuildingTypeId() {
        return (oracle.jbo.domain.Number) getAttributeInternal(PARENTBUILDINGTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParentBuildingTypeId.
     * @param value value to set the ParentBuildingTypeId
     */
    public void setParentBuildingTypeId(Number value) {
        setAttributeInternal(PARENTBUILDINGTYPEID, value);
    }

    /**
     * Gets the attribute value for BuildingTypeName, using the alias name BuildingTypeName.
     * @return the value of BuildingTypeName
     */
    public String getBuildingTypeName() {
        return (String) getAttributeInternal(BUILDINGTYPENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuildingTypeName.
     * @param value value to set the BuildingTypeName
     */
    public void setBuildingTypeName(String value) {
        setAttributeInternal(BUILDINGTYPENAME, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the value of LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for IntAttributeCategory, using the alias name IntAttributeCategory.
     * @return the value of IntAttributeCategory
     */
    public String getIntAttributeCategory() {
        return (String) getAttributeInternal(INTATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntAttributeCategory.
     * @param value value to set the IntAttributeCategory
     */
    public void setIntAttributeCategory(String value) {
        setAttributeInternal(INTATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for IntAttribute1, using the alias name IntAttribute1.
     * @return the value of IntAttribute1
     */
    public String getIntAttribute1() {
        return (String) getAttributeInternal(INTATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntAttribute1.
     * @param value value to set the IntAttribute1
     */
    public void setIntAttribute1(String value) {
        setAttributeInternal(INTATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for IntAttribute2, using the alias name IntAttribute2.
     * @return the value of IntAttribute2
     */
    public String getIntAttribute2() {
        return (String) getAttributeInternal(INTATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntAttribute2.
     * @param value value to set the IntAttribute2
     */
    public void setIntAttribute2(String value) {
        setAttributeInternal(INTATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for IntAttribute3, using the alias name IntAttribute3.
     * @return the value of IntAttribute3
     */
    public String getIntAttribute3() {
        return (String) getAttributeInternal(INTATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntAttribute3.
     * @param value value to set the IntAttribute3
     */
    public void setIntAttribute3(String value) {
        setAttributeInternal(INTATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for IntAttribute4, using the alias name IntAttribute4.
     * @return the value of IntAttribute4
     */
    public String getIntAttribute4() {
        return (String) getAttributeInternal(INTATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntAttribute4.
     * @param value value to set the IntAttribute4
     */
    public void setIntAttribute4(String value) {
        setAttributeInternal(INTATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for IntAttribute5, using the alias name IntAttribute5.
     * @return the value of IntAttribute5
     */
    public String getIntAttribute5() {
        return (String) getAttributeInternal(INTATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntAttribute5.
     * @param value value to set the IntAttribute5
     */
    public void setIntAttribute5(String value) {
        setAttributeInternal(INTATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for IntAttribute6, using the alias name IntAttribute6.
     * @return the value of IntAttribute6
     */
    public String getIntAttribute6() {
        return (String) getAttributeInternal(INTATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntAttribute6.
     * @param value value to set the IntAttribute6
     */
    public void setIntAttribute6(String value) {
        setAttributeInternal(INTATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for IntAttribute7, using the alias name IntAttribute7.
     * @return the value of IntAttribute7
     */
    public String getIntAttribute7() {
        return (String) getAttributeInternal(INTATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntAttribute7.
     * @param value value to set the IntAttribute7
     */
    public void setIntAttribute7(String value) {
        setAttributeInternal(INTATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for IntAttribute8, using the alias name IntAttribute8.
     * @return the value of IntAttribute8
     */
    public String getIntAttribute8() {
        return (String) getAttributeInternal(INTATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntAttribute8.
     * @param value value to set the IntAttribute8
     */
    public void setIntAttribute8(String value) {
        setAttributeInternal(INTATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for IntAttribute9, using the alias name IntAttribute9.
     * @return the value of IntAttribute9
     */
    public String getIntAttribute9() {
        return (String) getAttributeInternal(INTATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntAttribute9.
     * @param value value to set the IntAttribute9
     */
    public void setIntAttribute9(String value) {
        setAttributeInternal(INTATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for IntAttribute10, using the alias name IntAttribute10.
     * @return the value of IntAttribute10
     */
    public String getIntAttribute10() {
        return (String) getAttributeInternal(INTATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntAttribute10.
     * @param value value to set the IntAttribute10
     */
    public void setIntAttribute10(String value) {
        setAttributeInternal(INTATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for IntAttribute11, using the alias name IntAttribute11.
     * @return the value of IntAttribute11
     */
    public String getIntAttribute11() {
        return (String) getAttributeInternal(INTATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntAttribute11.
     * @param value value to set the IntAttribute11
     */
    public void setIntAttribute11(String value) {
        setAttributeInternal(INTATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for IntAttribute12, using the alias name IntAttribute12.
     * @return the value of IntAttribute12
     */
    public String getIntAttribute12() {
        return (String) getAttributeInternal(INTATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntAttribute12.
     * @param value value to set the IntAttribute12
     */
    public void setIntAttribute12(String value) {
        setAttributeInternal(INTATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for IntAttribute13, using the alias name IntAttribute13.
     * @return the value of IntAttribute13
     */
    public String getIntAttribute13() {
        return (String) getAttributeInternal(INTATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntAttribute13.
     * @param value value to set the IntAttribute13
     */
    public void setIntAttribute13(String value) {
        setAttributeInternal(INTATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for IntAttribute14, using the alias name IntAttribute14.
     * @return the value of IntAttribute14
     */
    public String getIntAttribute14() {
        return (String) getAttributeInternal(INTATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntAttribute14.
     * @param value value to set the IntAttribute14
     */
    public void setIntAttribute14(String value) {
        setAttributeInternal(INTATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for IntAttribute15, using the alias name IntAttribute15.
     * @return the value of IntAttribute15
     */
    public String getIntAttribute15() {
        return (String) getAttributeInternal(INTATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntAttribute15.
     * @param value value to set the IntAttribute15
     */
    public void setIntAttribute15(String value) {
        setAttributeInternal(INTATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for ExtAttributeCategory, using the alias name ExtAttributeCategory.
     * @return the value of ExtAttributeCategory
     */
    public String getExtAttributeCategory() {
        return (String) getAttributeInternal(EXTATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttributeCategory.
     * @param value value to set the ExtAttributeCategory
     */
    public void setExtAttributeCategory(String value) {
        setAttributeInternal(EXTATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for ExtAttribute1, using the alias name ExtAttribute1.
     * @return the value of ExtAttribute1
     */
    public String getExtAttribute1() {
        return (String) getAttributeInternal(EXTATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute1.
     * @param value value to set the ExtAttribute1
     */
    public void setExtAttribute1(String value) {
        setAttributeInternal(EXTATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ExtAttribute2, using the alias name ExtAttribute2.
     * @return the value of ExtAttribute2
     */
    public String getExtAttribute2() {
        return (String) getAttributeInternal(EXTATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute2.
     * @param value value to set the ExtAttribute2
     */
    public void setExtAttribute2(String value) {
        setAttributeInternal(EXTATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ExtAttribute3, using the alias name ExtAttribute3.
     * @return the value of ExtAttribute3
     */
    public String getExtAttribute3() {
        return (String) getAttributeInternal(EXTATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute3.
     * @param value value to set the ExtAttribute3
     */
    public void setExtAttribute3(String value) {
        setAttributeInternal(EXTATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ExtAttribute4, using the alias name ExtAttribute4.
     * @return the value of ExtAttribute4
     */
    public String getExtAttribute4() {
        return (String) getAttributeInternal(EXTATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute4.
     * @param value value to set the ExtAttribute4
     */
    public void setExtAttribute4(String value) {
        setAttributeInternal(EXTATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ExtAttribute5, using the alias name ExtAttribute5.
     * @return the value of ExtAttribute5
     */
    public String getExtAttribute5() {
        return (String) getAttributeInternal(EXTATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute5.
     * @param value value to set the ExtAttribute5
     */
    public void setExtAttribute5(String value) {
        setAttributeInternal(EXTATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ExtAttribute6, using the alias name ExtAttribute6.
     * @return the value of ExtAttribute6
     */
    public String getExtAttribute6() {
        return (String) getAttributeInternal(EXTATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute6.
     * @param value value to set the ExtAttribute6
     */
    public void setExtAttribute6(String value) {
        setAttributeInternal(EXTATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ExtAttribute7, using the alias name ExtAttribute7.
     * @return the value of ExtAttribute7
     */
    public String getExtAttribute7() {
        return (String) getAttributeInternal(EXTATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute7.
     * @param value value to set the ExtAttribute7
     */
    public void setExtAttribute7(String value) {
        setAttributeInternal(EXTATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ExtAttribute8, using the alias name ExtAttribute8.
     * @return the value of ExtAttribute8
     */
    public String getExtAttribute8() {
        return (String) getAttributeInternal(EXTATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute8.
     * @param value value to set the ExtAttribute8
     */
    public void setExtAttribute8(String value) {
        setAttributeInternal(EXTATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ExtAttribute9, using the alias name ExtAttribute9.
     * @return the value of ExtAttribute9
     */
    public String getExtAttribute9() {
        return (String) getAttributeInternal(EXTATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute9.
     * @param value value to set the ExtAttribute9
     */
    public void setExtAttribute9(String value) {
        setAttributeInternal(EXTATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ExtAttribute10, using the alias name ExtAttribute10.
     * @return the value of ExtAttribute10
     */
    public String getExtAttribute10() {
        return (String) getAttributeInternal(EXTATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute10.
     * @param value value to set the ExtAttribute10
     */
    public void setExtAttribute10(String value) {
        setAttributeInternal(EXTATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ExtAttribute11, using the alias name ExtAttribute11.
     * @return the value of ExtAttribute11
     */
    public String getExtAttribute11() {
        return (String) getAttributeInternal(EXTATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute11.
     * @param value value to set the ExtAttribute11
     */
    public void setExtAttribute11(String value) {
        setAttributeInternal(EXTATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ExtAttribute12, using the alias name ExtAttribute12.
     * @return the value of ExtAttribute12
     */
    public String getExtAttribute12() {
        return (String) getAttributeInternal(EXTATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute12.
     * @param value value to set the ExtAttribute12
     */
    public void setExtAttribute12(String value) {
        setAttributeInternal(EXTATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ExtAttribute13, using the alias name ExtAttribute13.
     * @return the value of ExtAttribute13
     */
    public String getExtAttribute13() {
        return (String) getAttributeInternal(EXTATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute13.
     * @param value value to set the ExtAttribute13
     */
    public void setExtAttribute13(String value) {
        setAttributeInternal(EXTATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ExtAttribute14, using the alias name ExtAttribute14.
     * @return the value of ExtAttribute14
     */
    public String getExtAttribute14() {
        return (String) getAttributeInternal(EXTATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute14.
     * @param value value to set the ExtAttribute14
     */
    public void setExtAttribute14(String value) {
        setAttributeInternal(EXTATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ExtAttribute15, using the alias name ExtAttribute15.
     * @return the value of ExtAttribute15
     */
    public String getExtAttribute15() {
        return (String) getAttributeInternal(EXTATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtAttribute15.
     * @param value value to set the ExtAttribute15
     */
    public void setExtAttribute15(String value) {
        setAttributeInternal(EXTATTRIBUTE15, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param buildingTypeId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number buildingTypeId) {
        return new Key(new Object[] { buildingTypeId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seq =
            new SequenceImpl("XXMA.XXMA_BUILDING_TYPES_SEQ", getDBTransaction());
        setBuildingTypeId(seq.getSequenceNumber());
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

