package ma.oracle.apps.cx.realestate.services.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 17 12:52:34 EET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MAProjPropServicesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MAProjPropServicesVOImpl() {
    }

    /**
     * Returns the bind variable value for P_PROJECT_ID.
     * @return bind variable value for P_PROJECT_ID
     */
    public String getP_PROJECT_ID() {
        return (String) getNamedWhereClauseParam("P_PROJECT_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_PROJECT_ID.
     * @param value value to bind as P_PROJECT_ID
     */
    public void setP_PROJECT_ID(String value) {
        setNamedWhereClauseParam("P_PROJECT_ID", value);
    }
}

