package ma.oracle.apps.cx.realestate.property.modules.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 22 13:03:01 EEST 2018
// ---------------------------------------------------------------------
public interface MARealEstatePropertyAM extends ApplicationModule {
    void gridViewEdit(Number propId);

    void fakeDelete(Number propId);

    void servicesRequery();

    String checkDuplicateFile(String fileNm);

    void setFileData(String name, String path, String contTyp);

    String checkAttachDuplicateFile(String fileNm);

    void setAttachFileData(String name, String path, String contTyp);

    String checkBuildAttachDuplicateFile(String fileNm);

    void setBuildAttachFileData(String name, String path, String contTyp);

    String checkPropAttachDuplicateFile(String fileNm);

    void createBuildRentOption();

    void createBuilding();

    void createPropRentOption();

    void createProperty();

    void setPropAttachFileData(String name, String path, String contTyp);

    void ar_lang();

    void en_lang();
}
