package ma.oracle.apps.cx.realestate.payments.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 17 15:02:26 EET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MARentPaymentTermsDetailsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MARentPaymentTermsDetailsVOImpl() {
    }
}

